// ====== OFFLINE FICTION CONTENT PACKS (all topics) ======
// Each episode is self-contained so a randomly assembled story stays coherent
// and the questions derived from it are always correct.
// Slot grammar:
//   want:     completes "[NAME] ____."        e.g. "wanted to find the lost kite"
//   trigger:  completes "One day, [NAME] ____." (past-tense verb phrase)
//   problem:  completes "But ____."            (clause)
//   help:     completes "Then ____."           (clause)
//   solution: completes "[NAME] ____, and felt very <feeling>."
//   lesson:   completes "From that day on, [NAME] knew that ____."
//   mainIdea: completes "A <kind> who ____."   (3rd-person verb phrase)

const FICTION_PACKS = {
  animals: {
    heroes:[{name:'Finn',kind:'fox'},{name:'Pip',kind:'rabbit'},{name:'Rosa',kind:'deer'},{name:'Milo',kind:'badger'}],
    settings:[{prose:'near a big green hill',label:'By a green hill'},{prose:'deep in a cozy forest',label:'In the forest'},{prose:'beside a bubbling creek',label:'By a creek'}],
    episodes:[
      { feeling:'proud',
        want:'wanted to find the sweetest berries in the whole woods',
        trigger:'spotted a bush full of ripe berries at the top of a steep slope',
        problem:'the slope was rocky and a little scary to climb',
        help:'a friendly bird showed a gentle path that wound around the rocks',
        solution:'followed the easy path and filled a basket to the brim',
        lesson:'asking for help can make a hard job feel easy',
        mainIdea:'works with a friend to reach a tricky goal',
        detail:'The berries were [NAME]\'s very favorite snack.',
        extra:'[NAME] shared the berries with everyone back home.',
        vocab:{word:'gentle',sentence:'The gentle path was smooth and easy, not steep at all.',meaning:'soft and easy, not rough',distractors:['very loud and fast','tall and pointy','cold and wet']},
        titles:['The Berry Hunt','[NAME]\'s Big Climb','Berries on the Hill'],
        why:{q:'Why was [NAME] able to fill the basket?',a:'Because a friend showed an easier path',distractors:['Because the hill was made of candy','Because it started to rain','Because the basket was magic']} },
      { feeling:'happy',
        want:'wanted to build the warmest nest before the cold night came',
        trigger:'gathered soft moss and leaves from all around the meadow',
        problem:'a gust of wind blew the pile away across the grass',
        help:'two little friends came running to help catch every leaf',
        solution:'tucked the nest into a safe hollow and made it snug',
        lesson:'good friends turn a big job into a fun one',
        mainIdea:'builds a cozy home with the help of friends',
        detail:'The night was going to be very chilly.',
        extra:'Everyone curled up together, warm and safe.',
        vocab:{word:'snug',sentence:'Inside the hollow it was snug, warm, and out of the wind.',meaning:'warm and cozy',distractors:['wet and muddy','big and empty','bright and noisy']},
        titles:['The Cozy Nest','A Warm Night','[NAME] Builds a Home'],
        why:{q:'Why did [NAME] need help?',a:'Because the wind kept blowing the nest away',distractors:['Because it was a sunny day','Because the nest was too heavy','Because [NAME] was sleepy']} },
      { feeling:'curious',
        want:'wanted to find a faster way home before the sky turned dark',
        trigger:'wandered a little too far chasing a butterfly through the trees',
        problem:'every path looked the same and home felt impossible to find',
        help:'a wise old owl pointed out a trail of familiar pawprints',
        solution:'followed the pawprints step by step until the den came into view',
        lesson:'staying calm helps you think your way out of trouble',
        mainIdea:'gets lost and finds the way back home',
        detail:'The woods looked very different once the sun started to set.',
        extra:'[NAME] promised to stay closer to home next time.',
        vocab:{word:'familiar',sentence:'The familiar pawprints looked just like the ones from home.',meaning:'known well, not strange',distractors:['brand new and shiny','far away and tiny','loud and scary']},
        titles:['Finding the Way Home','[NAME] Gets Lost','The Trail of Pawprints'],
        why:{q:'How did [NAME] find the way home?',a:'By following a trail of familiar pawprints',distractors:['By flying over the trees','By asking a fish','By waiting for rain']} },
      { feeling:'cheerful',
        want:'wanted to gather enough acorns to share before the snow came',
        trigger:'spotted a tree dropping acorns all over the forest floor',
        problem:'carrying so many acorns alone was much too hard',
        help:'a cheerful squirrel friend offered to help carry a second pile',
        solution:'stacked two big piles safely inside a cozy hollow log',
        lesson:'sharing the work makes a big job feel small',
        mainIdea:'gathers food for winter with a helpful friend',
        detail:'Acorns are a favorite winter snack for many forest animals.',
        extra:'[NAME] saved a few acorns to plant a new tree in spring.',
        vocab:{word:'hollow',sentence:'The hollow log had a big empty space perfect for storing food.',meaning:'having an empty space inside',distractors:['full and heavy','tall and thin','wet and shiny']},
        titles:['The Acorn Pile','[NAME] Gets Ready for Winter','Sharing the Harvest'],
        why:{q:'Why did [NAME] need help carrying the acorns?',a:'There were too many acorns to carry alone',distractors:['The acorns were too small','It started to rain','The log was too far']} },
    ],
  },
  space: {
    heroes:[{name:'Luna',kind:'astronaut'},{name:'Zip',kind:'little robot'},{name:'Cosmo',kind:'star sprite'},{name:'Ravi',kind:'space cadet'}],
    settings:[{prose:'on a shiny silver space station',label:'On a space station'},{prose:'aboard a tiny rocket ship',label:'In a rocket'},{prose:'on a quiet moon base',label:'On the moon'}],
    episodes:[
      { feeling:'excited',
        want:'wanted to see the rings of a faraway planet up close',
        trigger:'pointed the little rocket toward the glowing planet',
        problem:'a cloud of space dust hid the rings from view',
        help:'a wise old satellite beeped out the safest way around',
        solution:'steered gently past the dust and saw the rings sparkle',
        lesson:'patience helps you reach a faraway goal',
        mainIdea:'travels through space to discover something amazing',
        detail:'The rings shone like a giant golden hoop.',
        extra:'[NAME] drew a picture to remember the trip.',
        vocab:{word:'faraway',sentence:'The faraway planet was so distant it looked like a tiny dot.',meaning:'very far in distance',distractors:['close and near','small and round','warm and soft']},
        titles:['The Shining Rings','[NAME] in Space','A Trip to the Planet'],
        why:{q:'Why couldn\'t [NAME] see the rings at first?',a:'Because a cloud of space dust was in the way',distractors:['Because the rocket was upside down','Because it was nighttime','Because [NAME] closed both eyes']} },
      { feeling:'proud',
        want:'wanted to fix the blinking light on the space station',
        trigger:'floated down a long hallway toward the blinking control panel',
        problem:'the toolbox drifted away and bumped against the ceiling',
        help:'a kind crewmate grabbed the floating tools just in time',
        solution:'tightened the loose wire and made the light glow steady',
        lesson:'teamwork keeps everyone safe up in space',
        mainIdea:'fixes a problem on the station with a teammate',
        detail:'In space, things float if you let them go.',
        extra:'The whole crew cheered when the light came on.',
        vocab:{word:'drifted',sentence:'The toolbox drifted slowly away, floating in the air.',meaning:'floated slowly along',distractors:['fell down fast','stayed still','grew much bigger']},
        titles:['The Blinking Light','Fix-It in Space','[NAME] Saves the Day'],
        why:{q:'Why did the tools float away?',a:'Because things float in space',distractors:['Because the door was open','Because [NAME] threw them','Because they were too heavy']} },
      { feeling:'curious',
        want:'wanted to count every star in a brand-new corner of the sky',
        trigger:'aimed a big telescope at a sparkling patch of stars',
        problem:'the stars blurred together and were hard to tell apart',
        help:'a clever computer sorted the stars into neat little groups',
        solution:'counted each group and mapped the whole starry patch',
        lesson:'a good tool can make a tricky job much clearer',
        mainIdea:'uses a tool to study and count distant stars',
        detail:'Some of the stars were so far away their light took years to arrive.',
        extra:'[NAME] named one tiny star after a best friend back home.',
        vocab:{word:'blurred',sentence:'The stars blurred together, looking fuzzy instead of sharp.',meaning:'looked fuzzy and unclear',distractors:['looked very sharp','turned bright red','disappeared completely']},
        titles:['Counting the Stars','[NAME]\'s Starry Map','A New Corner of Sky'],
        why:{q:'How did [NAME] tell the stars apart?',a:'A computer sorted them into neat groups',distractors:['[NAME] guessed the number','The stars lined up alone','A friend counted by hand']} },
      { feeling:'brave',
        want:'wanted to repair a cracked window on the outside of the ship',
        trigger:'clipped on a safety line and floated out into open space',
        problem:'the crack was in an awkward spot, hard to reach',
        help:'a steady robotic arm held [NAME] safely in just the right place',
        solution:'patched the crack tight and tested it twice to be sure',
        lesson:'careful checking keeps everyone safe',
        mainIdea:'fixes a problem outside the ship with help from a tool',
        detail:'A spacesuit keeps an astronaut safe and breathing in space.',
        extra:'The whole crew thanked [NAME] for the careful work.',
        vocab:{word:'awkward',sentence:'The crack was in an awkward spot, tricky to reach from any angle.',meaning:'hard to handle or reach',distractors:['easy and simple','bright and shiny','soft and round']},
        titles:['The Cracked Window','[NAME] Makes Repairs','Out in Open Space'],
        why:{q:'Why was the crack hard to fix?',a:'It was in an awkward, hard-to-reach spot',distractors:['It was too small to see','It kept moving away','It was underwater']} },
    ],
  },
  ocean: {
    heroes:[{name:'Coral',kind:'sea turtle'},{name:'Bubbles',kind:'dolphin'},{name:'Finn',kind:'little fish'},{name:'Pearl',kind:'octopus'}],
    settings:[{prose:'in a colorful coral reef',label:'In a coral reef'},{prose:'near a sunken pirate ship',label:'By a sunken ship'},{prose:'in a quiet seagrass bay',label:'In a seagrass bay'}],
    episodes:[
      { feeling:'joyful',
        want:'wanted to find the lost pearl that fell from a giant clam',
        trigger:'searched between the swaying seagrass for a glint of white',
        problem:'the water grew dark and it was hard to see',
        help:'a glowing jellyfish lit the way with a soft blue shine',
        solution:'found the pearl tucked under a rock and carried it home',
        lesson:'a little light from a friend goes a long way',
        mainIdea:'searches the sea and finds a lost treasure',
        detail:'The pearl was as round as a marble.',
        extra:'The giant clam smiled a slow, happy smile.',
        vocab:{word:'glint',sentence:'A tiny glint of white sparkled between the green seagrass.',meaning:'a small flash of light',distractors:['a loud splash','a dark hole','a heavy rock']},
        titles:['The Lost Pearl','[NAME] and the Glow','Treasure in the Reef'],
        why:{q:'Why was it hard for [NAME] to see?',a:'Because the water grew dark',distractors:['Because [NAME] was sleeping','Because the sun was too bright','Because the pearl was loud']} },
      { feeling:'grateful',
        want:'wanted to free a friend tangled in an old fishing net',
        trigger:'swam fast toward a soft, worried cry near the reef',
        problem:'the net was knotted tight and would not come loose',
        help:'a clever crab snipped the ropes with two strong claws',
        solution:'pulled the net away and set the friend free at last',
        lesson:'helping others is the kindest thing you can do',
        mainIdea:'rescues a friend who is in trouble',
        detail:'The net had drifted in from far away.',
        extra:'The two friends did a happy loop together.',
        vocab:{word:'tangled',sentence:'The net was tangled, with ropes twisted all around.',meaning:'twisted up in knots',distractors:['shiny and new','flat and smooth','small and dry']},
        titles:['The Tangled Net','[NAME] to the Rescue','Free Again'],
        why:{q:'How was the friend set free?',a:'A crab snipped the ropes with its claws',distractors:['The net melted in the sun','A wave washed it away','[NAME] sang a song']} },
      { feeling:'excited',
        want:'wanted to explore inside the old sunken ship for the first time',
        trigger:'peeked through a round window into the quiet, dark ship',
        problem:'it was much too dark inside to see anything at all',
        help:'a school of glowing fish swam in to light up every corner',
        solution:'explored each room and found a chest of old shiny coins',
        lesson:'a little light from friends can open up a whole new world',
        mainIdea:'explores a sunken ship with help from glowing friends',
        detail:'Ships that sink can become new homes for ocean creatures.',
        extra:'[NAME] left the coins for new friends to discover later.',
        vocab:{word:'explore',sentence:'It was exciting to explore, looking around a brand-new place.',meaning:'to look around and discover new things',distractors:['to hide away','to swim home fast','to take a long nap']},
        titles:['The Sunken Ship','[NAME] Goes Exploring','Treasure in the Dark'],
        why:{q:'How did [NAME] see inside the dark ship?',a:'Glowing fish lit up the rooms',distractors:['The sun shone underwater','[NAME] used a flashlight','The ship had windows everywhere']} },
      { feeling:'proud',
        want:'wanted to teach a younger fish how to hide safely from danger',
        trigger:'noticed a tiny fish swimming out in the open, easy to spot',
        problem:'a hungry shark was circling closer every minute',
        help:'showed the little fish how to dart into a clump of seagrass',
        solution:'hid together until the shark swam away and lost interest',
        lesson:'sharing what you know keeps everyone safer',
        mainIdea:'teaches a younger fish how to stay safe',
        detail:'Seagrass makes a great hiding spot because it sways like the fish.',
        extra:'The little fish practiced the trick all on its own the next day.',
        vocab:{word:'circling',sentence:'The shark was circling, swimming round and round nearby.',meaning:'moving round and round something',distractors:['swimming straight away','sleeping at the bottom','jumping out of the water']},
        titles:['Hiding in the Seagrass','[NAME] Teaches a Trick','Safe from the Shark'],
        why:{q:'How did the little fish stay safe?',a:'It hid in a clump of swaying seagrass',distractors:['It swam faster than the shark','It turned invisible','It called for a boat']} },
    ],
  },
  weather: {
    heroes:[{name:'Sky',kind:'cloud sprite'},{name:'Dewey',kind:'raindrop'},{name:'Sunny',kind:'sunbeam'},{name:'Gale',kind:'wind whisp'}],
    settings:[{prose:'high up in the fluffy clouds',label:'In the clouds'},{prose:'over a green farm valley',label:'Over a valley'},{prose:'above a sleepy little town',label:'Above a town'}],
    episodes:[
      { feeling:'happy',
        want:'wanted to water the thirsty flowers in the valley below',
        trigger:'gathered a big puffy cloud full of cool raindrops',
        problem:'a strong wind pushed the cloud the wrong way',
        help:'a gentle breeze nudged the cloud back over the flowers',
        solution:'let the rain fall softly until every flower had a drink',
        lesson:'even the weather works best when friends team up',
        mainIdea:'brings rain to help the thirsty flowers grow',
        detail:'The flowers had been droopy and dry all week.',
        extra:'A bright rainbow stretched across the sky after.',
        vocab:{word:'thirsty',sentence:'The thirsty flowers had no water and looked very droopy.',meaning:'needing water badly',distractors:['full of water','tall and strong','red and shiny']},
        titles:['The Rain Helper','[NAME] and the Flowers','A Drink for the Valley'],
        why:{q:'Why did the flowers need [NAME]?',a:'Because they were thirsty and dry',distractors:['Because they were too wet','Because they were lost','Because they wanted shade']} },
      { feeling:'proud',
        want:'wanted to clear the fog so the town could see the morning sun',
        trigger:'floated low over the streets where thick fog had settled',
        problem:'the fog was so heavy that no one could find their way',
        help:'a warm sunbeam joined in to lift the mist away',
        solution:'swept the fog up high until the whole town sparkled',
        lesson:'a little warmth can clear away a gloomy day',
        mainIdea:'clears the fog so the town can see again',
        detail:'The fog had hidden every roof and tree.',
        extra:'The townsfolk waved up at the bright clear sky.',
        vocab:{word:'mist',sentence:'The mist was a thin, damp cloud floating near the ground.',meaning:'a thin, damp cloud near the ground',distractors:['a pile of dry leaves','a loud thunder boom','a warm sunny beam']},
        titles:['Clearing the Fog','[NAME] and the Sun','A Bright Morning'],
        why:{q:'How was the fog cleared away?',a:'A warm sunbeam helped lift the mist',distractors:['A truck blew it away','It turned into snow','[NAME] ate it up']} },
      { feeling:'curious',
        want:'wanted to find out where the wind goes after it blows past',
        trigger:'chased a swirl of leaves carried along by a gentle breeze',
        problem:'the wind moved faster than [NAME] could follow on foot',
        help:'a friendly cloud offered a ride high above the treetops',
        solution:'rode along and watched the wind swirl all the way to the sea',
        lesson:'sometimes the best way to learn is to go along for the ride',
        mainIdea:'follows the wind to learn where it travels',
        detail:'Wind is just air moving from one place to another.',
        extra:'[NAME] waved down at the tiny houses far below.',
        vocab:{word:'swirl',sentence:'The leaves swirl, spinning round and round in the breeze.',meaning:'to move round and round',distractors:['to sit very still','to fall straight down','to turn bright colors']},
        titles:['Chasing the Wind','[NAME]\'s Big Ride','Where the Wind Goes'],
        why:{q:'How did [NAME] keep up with the wind?',a:'A friendly cloud gave a ride above the treetops',distractors:['[NAME] grew wings','The wind stopped moving','A car gave a ride']} },
      { feeling:'happy',
        want:'wanted to make the very first snowflake of the season extra special',
        trigger:'gathered tiny bits of ice high in a chilly winter cloud',
        problem:'the ice kept melting before it could turn into snow',
        help:'a cold gust of wind chilled the air just enough',
        solution:'froze into a perfect, sparkly snowflake and drifted down to earth',
        lesson:'sometimes you need just the right help to finish a job',
        mainIdea:'makes the first snowflake of winter with help from the wind',
        detail:'No two snowflakes ever look exactly the same.',
        extra:'A child below caught the snowflake and smiled up at the sky.',
        vocab:{word:'chilly',sentence:'The chilly air felt cold enough to turn the ice into snow.',meaning:'cold or cool',distractors:['warm and sunny','loud and bright','wet and muddy']},
        titles:['The First Snowflake','[NAME] Makes Snow','A Sparkly Surprise'],
        why:{q:'Why did the ice keep melting at first?',a:'The air was not cold enough yet',distractors:['The ice was too heavy','The sun was too far away','The wind blew too softly']} },
    ],
  },
  friendship: {
    heroes:[{name:'Mia',kind:'girl'},{name:'Theo',kind:'boy'},{name:'Ruby',kind:'kid'},{name:'Sam',kind:'child'}],
    settings:[{prose:'in a sunny school yard',label:'At the school yard'},{prose:'on a friendly neighborhood street',label:'On their street'},{prose:'at a bright community park',label:'At the park'}],
    episodes:[
      { feeling:'happy',
        want:'wanted to cheer up a new friend who felt left out',
        trigger:'noticed a new kid sitting all alone at the edge of the yard',
        problem:'the new kid was too shy to come and play',
        help:'a couple of classmates brought over a ball and a big smile',
        solution:'invited the new friend into the game and played together',
        lesson:'a kind invitation can turn a stranger into a friend',
        mainIdea:'helps a lonely classmate feel welcome',
        detail:'It is no fun to feel left out.',
        extra:'By lunchtime they were all laughing together.',
        vocab:{word:'shy',sentence:'The new kid felt shy and was too nervous to say hello.',meaning:'quiet and nervous around others',distractors:['loud and bossy','sleepy and slow','fast and strong']},
        titles:['A New Friend','[NAME] Says Hello','Come Play!'],
        why:{q:'Why did the new kid sit alone at first?',a:'Because the new kid was too shy to join',distractors:['Because the yard was closed','Because it was raining','Because the kid was angry']} },
      { feeling:'grateful',
        want:'wanted to make up after a silly argument with a best friend',
        trigger:'remembered the fun the two friends always had together',
        problem:'both friends felt too stubborn to say sorry first',
        help:'a kind teacher reminded them how much they cared',
        solution:'said sorry at the same time and shared a big laugh',
        lesson:'saying sorry is brave, and it mends a friendship',
        mainIdea:'makes up with a friend after a fight',
        detail:'The argument had started over something very small.',
        extra:'They promised to talk it out next time.',
        vocab:{word:'stubborn',sentence:'They were both stubborn and would not give in or say sorry.',meaning:'not willing to change your mind',distractors:['happy and silly','quick and clever','kind and gentle']},
        titles:['Friends Again','The Big Sorry','[NAME] Makes Up'],
        why:{q:'Why didn\'t the friends make up right away?',a:'Because both were too stubborn to say sorry',distractors:['Because they moved away','Because school was over','Because they forgot each other']} },
      { feeling:'happy',
        want:'wanted to share a favorite book with a friend who had nothing to read',
        trigger:'noticed a friend looking bored during free reading time',
        problem:'there was only one copy of the favorite book to go around',
        help:'a teacher suggested taking turns reading it page by page',
        solution:'read the book together, swapping pages and giggling at the funny parts',
        lesson:'sharing turns one good thing into two good things',
        mainIdea:'shares a book with a friend who had nothing to read',
        detail:'Reading together can be even more fun than reading alone.',
        extra:'They asked the librarian for a second copy the very next day.',
        vocab:{word:'swapping',sentence:'They kept swapping pages, trading turns reading the book.',meaning:'trading or exchanging',distractors:['hiding away','tearing apart','throwing far']},
        titles:['Sharing a Story','[NAME] and the Book','Take Turns, Have Fun'],
        why:{q:'How did the friends solve the book problem?',a:'They took turns reading page by page',distractors:['They bought ten more books','They stopped reading','They argued all day']} },
      { feeling:'grateful',
        want:'wanted to thank a friend who always helped without being asked',
        trigger:'thought about all the small ways a friend had helped all year',
        problem:'it was hard to find just the right way to say thank you',
        help:'a parent suggested making something by hand instead of buying it',
        solution:'made a thank-you card full of drawings and kind words',
        lesson:'a thoughtful gift means more than an expensive one',
        mainIdea:'makes a thank-you card for a helpful friend',
        detail:'Small acts of kindness add up to something big over time.',
        extra:'The friend kept the card pinned up for the rest of the year.',
        vocab:{word:'thoughtful',sentence:'The thoughtful card showed how much [NAME] had noticed and cared.',meaning:'showing care about others\' feelings',distractors:['loud and silly','fast and messy','cold and plain']},
        titles:['The Thank-You Card','[NAME] Says Thanks','A Gift From the Heart'],
        why:{q:'Why did [NAME] decide to make a card instead of buying one?',a:'A handmade gift felt more thoughtful',distractors:['The store was closed','Cards were too expensive','[NAME] forgot to shop']} },
    ],
  },
  sports: {
    heroes:[{name:'Jay',kind:'young player'},{name:'Lola',kind:'sprinter'},{name:'Marco',kind:'goalie'},{name:'Nia',kind:'gymnast'}],
    settings:[{prose:'on a grassy soccer field',label:'On the field'},{prose:'at a busy running track',label:'At the track'},{prose:'inside a bright gym',label:'In the gym'}],
    episodes:[
      { feeling:'proud',
        want:'wanted to score a goal in the big game on Saturday',
        trigger:'practiced kicking the ball again and again after school',
        problem:'every shot kept missing wide of the net',
        help:'a patient coach showed how to aim with the side of the foot',
        solution:'kicked it just right and the ball curved into the goal',
        lesson:'practice and good coaching make hard things possible',
        mainIdea:'practices hard to reach a sports goal',
        detail:'The big game was only a few days away.',
        extra:'The whole team jumped up and cheered.',
        vocab:{word:'aim',sentence:'The coach showed [NAME] how to aim, or point the kick, at the net.',meaning:'to point at a target',distractors:['to run away fast','to fall down','to take a nap']},
        titles:['The Big Goal','[NAME] Scores','Practice Pays Off'],
        why:{q:'Why did [NAME]\'s shots miss at first?',a:'Because [NAME] was not aiming the right way',distractors:['Because the ball was flat','Because it was too sunny','Because the net was gone']} },
      { feeling:'joyful',
        want:'wanted to finish the long race without giving up',
        trigger:'lined up at the start with butterflies in the tummy',
        problem:'halfway through, [NAME]\'s legs felt heavy and tired',
        help:'a teammate ran alongside and cheered every step',
        solution:'kept going all the way to the finish line, slow but steady',
        lesson:'finishing is a win, even if you are not the fastest',
        mainIdea:'keeps going in a race instead of giving up',
        detail:'The track went all the way around the field.',
        extra:'[NAME] got a shiny ribbon just for finishing.',
        vocab:{word:'steady',sentence:'[NAME] ran at a steady pace, the same speed the whole way.',meaning:'staying the same and even',distractors:['stopping and starting','very fast then slow','jumpy and wild']},
        titles:['The Long Race','Never Give Up','[NAME] Finishes Strong'],
        why:{q:'How did [NAME] finish the race?',a:'A teammate cheered and ran alongside',distractors:['A car gave a ride','The race was canceled','[NAME] flew over it']} },
      { feeling:'proud',
        want:'wanted to learn a brand-new gymnastics move before the big show',
        trigger:'tried the new move over and over on the soft practice mat',
        problem:'every try ended in a wobble and a tumble to the floor',
        help:'a patient coach broke the move into three smaller, easier steps',
        solution:'practiced each small step until the whole move felt smooth',
        lesson:'breaking a big challenge into small steps makes it possible',
        mainIdea:'learns a new skill by practicing it one step at a time',
        detail:'Even small wobbles are part of learning something new.',
        extra:'[NAME] landed the move perfectly in front of a cheering crowd.',
        vocab:{word:'wobble',sentence:'Every try ended in a wobble, a shaky loss of balance.',meaning:'to shake or move unsteadily',distractors:['to stand perfectly still','to jump very high','to land softly']},
        titles:['The New Move','[NAME] Practices','Step by Step'],
        why:{q:'How did [NAME] finally learn the move?',a:'By practicing it broken into smaller steps',distractors:['By watching it on television','By giving up and trying later','By asking a friend to do it instead']} },
      { feeling:'grateful',
        want:'wanted to stop a tricky shot during the most important game of the season',
        trigger:'crouched low in the goal as the other team raced toward the net',
        problem:'the shot came in fast, curving in an unexpected direction',
        help:'months of practice kicked in and quick reflexes took over',
        solution:'dove sideways and blocked the shot just in time',
        lesson:'practice pays off exactly when you need it most',
        mainIdea:'makes a big save thanks to months of practice',
        detail:'Goalies practice diving and blocking shots almost every day.',
        extra:'The whole team lifted [NAME] up to celebrate the save.',
        vocab:{word:'reflexes',sentence:'Quick reflexes helped [NAME] react before even thinking about it.',meaning:'fast, automatic reactions',distractors:['slow careful thoughts','loud cheering sounds','heavy training gear']},
        titles:['The Big Save','[NAME] Blocks the Shot','Ready for Anything'],
        why:{q:'Why was [NAME] able to block the tricky shot?',a:'Months of practice had built quick reflexes',distractors:['The ball moved slowly','A teammate caught it first','The goal was very small']} },
    ],
  },
  dinosaurs: {
    heroes:[{name:'Trudy',kind:'triceratops'},{name:'Rex',kind:'little raptor'},{name:'Spike',kind:'stegosaurus'},{name:'Dot',kind:'baby dino'}],
    settings:[{prose:'in a steamy green jungle',label:'In the jungle'},{prose:'near a wide muddy river',label:'By the river'},{prose:'at the foot of a smoky volcano',label:'By the volcano'}],
    episodes:[
      { feeling:'brave',
        want:'wanted to find the tastiest leaves on the tallest tree',
        trigger:'stretched a long neck up toward the leafy branches',
        problem:'the branches were far too high to reach',
        help:'a tall friend offered a strong back to stand on',
        solution:'climbed up just enough to nibble the juicy leaves',
        lesson:'a good friend can help you reach new heights',
        mainIdea:'works with a friend to reach high leaves',
        detail:'The leaves at the top were the greenest of all.',
        extra:'They shared the leaves and munched happily.',
        vocab:{word:'stretched',sentence:'[NAME] stretched, making the neck as long as it could go.',meaning:'reached out as far as possible',distractors:['curled up tight','sat down to rest','rolled in the mud']},
        titles:['The Tall Tree','[NAME] Reaches High','Leafy Lunch'],
        why:{q:'Why couldn\'t [NAME] reach the leaves alone?',a:'Because the branches were too high',distractors:['Because the tree was tiny','Because [NAME] was full','Because it was raining']} },
      { feeling:'happy',
        want:'wanted to cross the wide river to reach a berry patch',
        trigger:'looked for a safe place to step across the rushing water',
        problem:'the water was deep and moved very fast',
        help:'a row of friendly dinos made a bridge with their backs',
        solution:'crossed step by step and reached the sweet berries',
        lesson:'big problems shrink when everyone pitches in',
        mainIdea:'crosses a river with help from friends',
        detail:'The berry patch was bright red and ripe.',
        extra:'Everyone shared a berry feast on the far bank.',
        vocab:{word:'rushing',sentence:'The rushing river moved fast, splashing over the rocks.',meaning:'moving very fast',distractors:['frozen and still','warm and calm','dry and empty']},
        titles:['Across the River','The Dino Bridge','[NAME]\'s Big Crossing'],
        why:{q:'How did [NAME] cross the river?',a:'Friends made a bridge with their backs',distractors:['[NAME] swam very fast','A boat appeared','The river dried up']} },
      { feeling:'brave',
        want:'wanted to find a safe path away from the rumbling volcano',
        trigger:'felt the ground shake as smoke curled up from the mountain',
        problem:'every direction looked the same in the thick gray smoke',
        help:'a sharp-eyed friend spotted a clear trail leading toward the river',
        solution:'led the whole group safely down to the cool riverbank',
        lesson:'staying calm and watching closely helps you find a safe path',
        mainIdea:'leads a group of friends safely away from danger',
        detail:'Long ago, volcanoes sometimes rumbled and sent up clouds of smoke.',
        extra:'Everyone took a long drink of cool water once they were safe.',
        vocab:{word:'rumbling',sentence:'The rumbling ground shook gently under everyone\'s feet.',meaning:'making a deep, rolling sound or shaking',distractors:['standing perfectly still','glowing bright green','smelling very sweet']},
        titles:['Away from the Volcano','[NAME] Leads the Way','A Safe Path'],
        why:{q:'How did the group find a safe path?',a:'A sharp-eyed friend spotted a clear trail',distractors:['They followed the smoke','They waited for rain','They dug a tunnel']} },
      { feeling:'happy',
        want:'wanted to keep a newly hatched baby dino warm through a cool night',
        trigger:'noticed the tiny hatchling shivering near the nest',
        problem:'the night air was much colder than the warm afternoon',
        help:'several friends gathered close to share their body warmth',
        solution:'curled around the nest until the baby dino stopped shivering',
        lesson:'a circle of friends can keep anyone warm and safe',
        mainIdea:'helps keep a baby dinosaur warm through the night',
        detail:'A newly hatched dinosaur needed lots of care to grow strong.',
        extra:'By morning, the baby dino was chirping happily in the sun.',
        vocab:{word:'hatchling',sentence:'The tiny hatchling had just broken out of its egg.',meaning:'a baby animal that just hatched',distractors:['a fully grown adult','a kind of plant','a type of rock']},
        titles:['Keeping Warm','[NAME] and the Hatchling','A Cozy Circle'],
        why:{q:'How did the friends keep the baby dino warm?',a:'They curled around the nest to share warmth',distractors:['They lit a fire','They flew the baby south','They covered it in leaves']} },
    ],
  },
  'community helpers': {
    heroes:[{name:'Officer Dana',kind:'helper'},{name:'Nurse Ben',kind:'helper'},{name:'Captain Joy',kind:'firefighter'},{name:'Mr. Lee',kind:'mail carrier'}],
    settings:[{prose:'in a busy little town',label:'In town'},{prose:'on a friendly main street',label:'On Main Street'},{prose:'near the town fire station',label:'By the fire station'}],
    episodes:[
      { feeling:'proud',
        want:'wanted to help a lost puppy find its way back home',
        trigger:'spotted a tiny puppy shivering by the side of the road',
        problem:'no one knew which house the puppy belonged to',
        help:'a kind neighbor recognized the puppy\'s red collar',
        solution:'walked the puppy safely back to its happy family',
        lesson:'helpers keep the whole town safe and kind',
        mainIdea:'helps a lost puppy get back home',
        detail:'The puppy had a shiny red collar.',
        extra:'The family gave the puppy a big, gentle hug.',
        vocab:{word:'recognized',sentence:'A neighbor recognized the collar, knowing it from before.',meaning:'knew it from before',distractors:['lost it again','never saw it','painted it blue']},
        titles:['The Lost Puppy','[NAME] Helps Out','Home at Last'],
        why:{q:'How was the puppy\'s home found?',a:'A neighbor recognized its red collar',distractors:['The puppy spoke','It started to snow','The puppy was magic']} },
      { feeling:'grateful',
        want:'wanted to make sure everyone got to the library safely',
        trigger:'noticed cars zooming past the busy street corner',
        problem:'the little ones were afraid to cross on their own',
        help:'a crossing guard raised a bright stop sign with a smile',
        solution:'walked every child across the street, safe and sound',
        lesson:'when helpers do their job, everyone can feel safe',
        mainIdea:'helps people cross a busy street safely',
        detail:'The library had a brand-new story time.',
        extra:'Every child waved thank you on the way past.',
        vocab:{word:'zooming',sentence:'The cars were zooming, moving very fast down the street.',meaning:'moving very fast',distractors:['parked and still','rolling slowly','flying in the air']},
        titles:['Crossing Safely','[NAME] at the Corner','To the Library'],
        why:{q:'Why were the little ones afraid?',a:'Because cars were zooming past the corner',distractors:['Because it was dark out','Because the library was closed','Because they were hungry']} },
      { feeling:'proud',
        want:'wanted to help a family whose smoke alarm kept beeping all night',
        trigger:'visited the house early in the morning to check on the noise',
        problem:'the old alarm battery had run out and needed to be replaced',
        help:'a quick trip to the truck for a fresh battery solved the puzzle',
        solution:'fitted the new battery and tested the alarm until it worked',
        lesson:'small fixes can solve problems that feel big at first',
        mainIdea:'helps a family fix a beeping smoke alarm',
        detail:'A smoke alarm beeps on purpose when its battery gets low.',
        extra:'The family thanked [NAME] with a plate of warm cookies.',
        vocab:{word:'replaced',sentence:'The old battery was replaced with a brand-new one.',meaning:'swapped out for something new',distractors:['painted a new color','thrown far away','hidden in a drawer']},
        titles:['The Beeping Alarm','[NAME] Solves It','A Quiet Night'],
        why:{q:'Why was the smoke alarm beeping?',a:'Its battery had run out and needed replacing',distractors:['There was a real fire','It was broken forever','It liked to make noise']} },
      { feeling:'grateful',
        want:'wanted to make sure every package arrived before a big family trip',
        trigger:'checked a long list of homes waiting for important deliveries',
        problem:'one important package seemed to be missing from the bag',
        help:'a quick call to the sorting center tracked down where it was',
        solution:'picked up the missing package and delivered it just in time',
        lesson:'careful checking helps you fix a mistake before it becomes a problem',
        mainIdea:'tracks down a missing package before a big trip',
        detail:'Packages travel through several stops before reaching your door.',
        extra:'The family waved happily from their porch when it arrived.',
        vocab:{word:'tracked',sentence:'A quick call tracked the package, finding out exactly where it was.',meaning:'followed or found the location of something',distractors:['painted bright colors','thrown into the river','wrapped up tightly']},
        titles:['The Missing Package','[NAME] Tracks It Down','Just in Time'],
        why:{q:'How was the missing package found?',a:'A call to the sorting center tracked it down',distractors:['It walked home by itself','It was never found','A neighbor returned it']} },
    ],
  },
  camping: {
    heroes:[{name:'Tess',kind:'camper'},{name:'Owen',kind:'scout'},{name:'Ivy',kind:'hiker'},{name:'Max',kind:'kid'}],
    settings:[{prose:'in a tall pine forest',label:'In the pine woods'},{prose:'beside a calm blue lake',label:'By the lake'},{prose:'on a grassy mountain meadow',label:'On a meadow'}],
    episodes:[
      { feeling:'proud',
        want:'wanted to set up the tent before the sun went down',
        trigger:'spread out the tent poles and bright nylon cover',
        problem:'the poles kept slipping and the tent flopped over',
        help:'an older camper showed how to lock each pole in place',
        solution:'snapped the poles together and the tent stood up tall',
        lesson:'a new skill is easy once someone shows you how',
        mainIdea:'learns to put up a tent with help',
        detail:'The sky was turning pink and orange.',
        extra:'They roasted marshmallows once the tent was up.',
        vocab:{word:'slipping',sentence:'The poles kept slipping, sliding out of [NAME]\'s hands.',meaning:'sliding out of place',distractors:['holding tight','growing taller','turning warm']},
        titles:['Setting Up Camp','[NAME]\'s Tent','Before Dark'],
        why:{q:'Why did the tent keep flopping over?',a:'Because the poles kept slipping out',distractors:['Because the wind blew it','Because it was too heavy','Because a bear sat on it']} },
      { feeling:'excited',
        want:'wanted to follow the trail to a hidden waterfall',
        trigger:'set off down the winding path with a little map',
        problem:'the trail split in two and [NAME] wasn\'t sure which way',
        help:'a park ranger pointed to the marker on the right path',
        solution:'took the marked trail and found the sparkling waterfall',
        lesson:'reading the signs helps you find your way',
        mainIdea:'follows a trail to a hidden waterfall',
        detail:'The waterfall could be heard before it was seen.',
        extra:'[NAME] splashed in the cool misty spray.',
        vocab:{word:'winding',sentence:'The winding path curved this way and that through the trees.',meaning:'full of curves and turns',distractors:['short and straight','steep and tall','wet and slippery']},
        titles:['The Hidden Waterfall','Which Way?','[NAME] Finds the Falls'],
        why:{q:'How did [NAME] choose the right trail?',a:'A ranger pointed to the trail marker',distractors:['[NAME] flipped a coin','The waterfall called out','A map fell from the sky']} },
      { feeling:'happy',
        want:'wanted to catch a fish for dinner using a homemade fishing pole',
        trigger:'cast a simple line out into the calm, glassy lake',
        problem:'the fish kept nibbling and swimming away before the hook caught',
        help:'an experienced camper showed how to wait patiently and watch closely',
        solution:'felt a tug, reeled in slowly, and landed a shiny fish at last',
        lesson:'patience turns a near-miss into a win',
        mainIdea:'learns patience while fishing for dinner',
        detail:'A calm lake makes it easier to see when a fish bites the line.',
        extra:'The whole camp enjoyed fish for dinner that night.',
        vocab:{word:'patiently',sentence:'Waiting patiently meant staying calm and not giving up too soon.',meaning:'calmly, without rushing or giving up',distractors:['quickly and loudly','angrily and fast','sleepily and slow']},
        titles:['Fishing at the Lake','[NAME] Waits and Wins','Dinner From the Lake'],
        why:{q:'How did [NAME] finally catch a fish?',a:'By waiting patiently and watching closely',distractors:['By yelling at the water','By giving up and going home','By using a flashlight']} },
      { feeling:'excited',
        want:'wanted to spot a real wild animal on the very first night of camp',
        trigger:'sat quietly by the fire, watching the dark edge of the woods',
        problem:'every rustling sound seemed to come from somewhere different',
        help:'a ranger\'s flashlight beam finally caught a pair of glowing eyes',
        solution:'spotted a curious deer nibbling grass just beyond the firelight',
        lesson:'patience and quiet help you notice things you might otherwise miss',
        mainIdea:'spots a wild animal by staying quiet and patient',
        detail:'Many animals come out to feed once the sun goes down.',
        extra:'[NAME] drew a picture of the deer to remember the moment.',
        vocab:{word:'rustling',sentence:'A rustling sound came from the leaves moving in the dark woods.',meaning:'a soft, rough sound made by something moving',distractors:['a loud crashing bang','total silence','a bright flash of light']},
        titles:['The Wild Visitor','[NAME] Spots a Deer','Quiet by the Fire'],
        why:{q:'How did [NAME] finally spot the animal?',a:'A flashlight beam caught its glowing eyes',distractors:['The deer walked into the tent','It was painted on a sign','A loud noise scared it close']} },
    ],
  },
  insects: {
    heroes:[{name:'Buzz',kind:'honeybee'},{name:'Lily',kind:'ladybug'},{name:'Gus',kind:'ant'},{name:'Flit',kind:'butterfly'}],
    settings:[{prose:'in a sunny flower garden',label:'In the garden'},{prose:'on a tall blade of grass',label:'On the grass'},{prose:'under a big leafy plant',label:'Under a leaf'}],
    episodes:[
      { feeling:'happy',
        want:'wanted to carry a crumb of bread back to the ant hill',
        trigger:'found a crumb that was much bigger than expected',
        problem:'the crumb was far too heavy to lift alone',
        help:'a line of ant friends marched over to lend their legs',
        solution:'lifted the crumb together and carried it home',
        lesson:'many small helpers can move a big load',
        mainIdea:'works with others to carry something heavy',
        detail:'The crumb was as big as [NAME]\'s whole head.',
        extra:'The whole ant hill shared a tasty meal.',
        vocab:{word:'marched',sentence:'The ants marched, walking in a straight, steady line.',meaning:'walked in a steady line',distractors:['flew away fast','rolled in a ball','fell asleep']},
        titles:['The Heavy Crumb','[NAME] and the Ants','Teamwork!'],
        why:{q:'Why couldn\'t [NAME] carry the crumb alone?',a:'Because it was far too heavy',distractors:['Because it was too small','Because it was sticky','Because it floated away']} },
      { feeling:'joyful',
        want:'wanted to find the brightest flower full of sweet nectar',
        trigger:'flew over the garden looking for a flash of color',
        problem:'a gray cloud rolled in and hid the sun',
        help:'a friendly butterfly knew a patch that always bloomed',
        solution:'sipped the sweet nectar and danced from bloom to bloom',
        lesson:'a friend who knows the way is a wonderful gift',
        mainIdea:'searches the garden for sweet nectar',
        detail:'Nectar is the sweet juice deep inside a flower.',
        extra:'[NAME] hummed a happy buzzing tune.',
        vocab:{word:'nectar',sentence:'The flower was full of nectar, a sweet juice insects love.',meaning:'sweet juice inside a flower',distractors:['a green leaf','a hard seed','a drop of rain']},
        titles:['Sweet Nectar','[NAME] in the Garden','The Brightest Bloom'],
        why:{q:'How did [NAME] find the blooming flowers?',a:'A butterfly knew a patch that always bloomed',distractors:['[NAME] dug underground','The flowers shouted','It was pure luck']} },
      { feeling:'brave',
        want:'wanted to rescue a tiny friend stuck in a sticky spider web',
        trigger:'heard a soft buzzing cry coming from a nearby bush',
        problem:'the web\'s sticky threads held the friend tight in place',
        help:'a clever friend found a stick to gently peel the threads away',
        solution:'freed the trapped friend one careful thread at a time',
        lesson:'a calm plan can solve even a sticky problem',
        mainIdea:'rescues a friend stuck in a spider web',
        detail:'Spider webs are sticky so they can catch insects to eat.',
        extra:'The two friends flew home together, safe and free.',
        vocab:{word:'sticky',sentence:'The sticky web held tight to anything that touched it.',meaning:'able to stick to things easily',distractors:['smooth and slippery','cold and frozen','loud and noisy']},
        titles:['Stuck in the Web','[NAME] to the Rescue','A Careful Escape'],
        why:{q:'How was the trapped friend finally freed?',a:'A stick gently peeled the sticky threads away',distractors:['The web fell apart on its own','Rain washed it away','A bird carried it off']} },
      { feeling:'joyful',
        want:'wanted to find the perfect spot to hide from a curious bird',
        trigger:'noticed a hungry bird hopping closer along the garden path',
        problem:'every open spot in the garden felt much too easy to spot',
        help:'a leaf with matching colors made the perfect hiding place',
        solution:'tucked in among the leaves until the bird hopped away',
        lesson:'blending in can be the cleverest kind of hiding',
        mainIdea:'hides safely by blending in with the leaves',
        detail:'Some insects have colors that match their surroundings perfectly.',
        extra:'[NAME] giggled, safe and unseen, as the bird wandered off.',
        vocab:{word:'blending',sentence:'Blending in with the leaves made [NAME] almost impossible to see.',meaning:'matching in so well you are hard to notice',distractors:['standing out brightly','flying very high','making loud sounds']},
        titles:['Hiding From the Bird','[NAME] Blends In','Safe Among the Leaves'],
        why:{q:'How did [NAME] stay safe from the bird?',a:'By blending in with the colors of the leaves',distractors:['By flying far away fast','By making a loud noise','By calling for help']} },
    ],
  },
  holidays: {
    heroes:[{name:'Noor',kind:'kid'},{name:'Eli',kind:'child'},{name:'Aria',kind:'girl'},{name:'Diego',kind:'boy'}],
    settings:[{prose:'in a cozy decorated home',label:'At home'},{prose:'at a bright town festival',label:'At the festival'},{prose:'in a sparkly school hall',label:'At school'}],
    episodes:[
      { feeling:'joyful',
        want:'wanted to make a special surprise for the family holiday',
        trigger:'gathered paper, glue, and a jar of glitter at the table',
        problem:'the glitter spilled and made a big sparkly mess',
        help:'a grandparent gently helped sweep and start again',
        solution:'finished a beautiful card that made everyone smile',
        lesson:'a small mess is okay when you keep trying',
        mainIdea:'makes a holiday surprise for the family',
        detail:'The holiday was [NAME]\'s favorite time of year.',
        extra:'The card hung proudly on the wall all season.',
        vocab:{word:'gathered',sentence:'[NAME] gathered the supplies, collecting them in one place.',meaning:'collected together',distractors:['threw away','hid from sight','broke in two']},
        titles:['The Holiday Surprise','[NAME]\'s Card','A Sparkly Mess'],
        why:{q:'Why did [NAME] need to start again?',a:'Because the glitter spilled and made a mess',distractors:['Because the lights went out','Because the card flew away','Because it was bedtime']} },
      { feeling:'grateful',
        want:'wanted everyone to feel included at the big celebration',
        trigger:'noticed a quiet neighbor watching from the doorway',
        problem:'the neighbor wasn\'t sure if they were invited in',
        help:'the whole family waved and pulled up an extra chair',
        solution:'welcomed the neighbor to share the food and fun',
        lesson:'holidays are happiest when everyone is welcome',
        mainIdea:'makes sure a neighbor feels included',
        detail:'The table was full of warm, tasty food.',
        extra:'The neighbor brought a song to share, too.',
        vocab:{word:'included',sentence:'Everyone was included, with a place for each person.',meaning:'made part of the group',distractors:['left outside','sent away','kept secret']},
        titles:['A Warm Welcome','[NAME]\'s Big Heart','An Extra Chair'],
        why:{q:'Why did the neighbor wait in the doorway?',a:'Because they weren\'t sure they were invited',distractors:['Because the door was locked','Because it was raining','Because they were tired']} },
      { feeling:'happy',
        want:'wanted to learn a special holiday song to sing with the family',
        trigger:'listened closely as a grandparent hummed an old, favorite tune',
        problem:'the words came out jumbled every single time [NAME] tried',
        help:'singing the song slowly, line by line, made it easier to remember',
        solution:'sang the whole song proudly at the holiday gathering',
        lesson:'breaking something tricky into small pieces makes it easier to learn',
        mainIdea:'learns a holiday song to share with the family',
        detail:'Many holiday songs have been sung in families for a very long time.',
        extra:'Everyone joined in by the second time through.',
        vocab:{word:'tune',sentence:'The grandparent hummed a gentle tune that everyone loved.',meaning:'a simple piece of music',distractors:['a kind of food','a warm blanket','a loud noise']},
        titles:['The Holiday Song','[NAME] Learns to Sing','A Family Tune'],
        why:{q:'How did [NAME] finally learn the song?',a:'By practicing it slowly, line by line',distractors:['By reading it once','By giving up and humming','By asking someone else to sing it']} },
      { feeling:'proud',
        want:'wanted to set the table just right for the big holiday meal',
        trigger:'counted out plates, cups, and forks for the whole family',
        problem:'there were not quite enough chairs for every single guest',
        help:'a few extra chairs were found tucked away in a closet',
        solution:'set every place at the table with room for everyone to sit',
        lesson:'a little extra planning makes everyone feel welcome',
        mainIdea:'sets the table so everyone has a place at the holiday meal',
        detail:'A full table is one of the best parts of a holiday gathering.',
        extra:'Family members thanked [NAME] for the careful work.',
        vocab:{word:'tucked',sentence:'A few extra chairs were tucked away inside a small closet.',meaning:'put neatly into a small space',distractors:['thrown out the window','painted bright red','left out in the rain']},
        titles:['Setting the Table','[NAME] Gets Ready','Room for Everyone'],
        why:{q:'How did [NAME] solve the chair problem?',a:'Found extra chairs tucked away in a closet',distractors:['Asked guests to stand','Borrowed chairs from a neighbor only','Skipped a few guests']} },
    ],
  },
  food: {
    heroes:[{name:'Chef Pip',kind:'young cook'},{name:'Rosa',kind:'baker'},{name:'Sam',kind:'kid'},{name:'Mina',kind:'child'}],
    settings:[{prose:'in a warm little kitchen',label:'In the kitchen'},{prose:'at a busy farmers market',label:'At the market'},{prose:'in a sunny backyard garden',label:'In the garden'}],
    episodes:[
      { feeling:'proud',
        want:'wanted to bake muffins for the whole class',
        trigger:'mixed the flour, eggs, and ripe mashed bananas',
        problem:'the batter looked too runny to bake just right',
        help:'a parent showed how to add a little more flour',
        solution:'baked a tray of golden muffins that smelled amazing',
        lesson:'following good steps turns a flop into a treat',
        mainIdea:'bakes a treat to share with others',
        detail:'Banana muffins were the class\'s favorite.',
        extra:'Every muffin was gone by the end of the day.',
        vocab:{word:'batter',sentence:'The batter was the soft, wet mix before it was baked.',meaning:'the wet mix before baking',distractors:['the empty pan','the cooled treat','the cold milk']},
        titles:['Muffin Day','[NAME] Bakes','The Golden Treat'],
        why:{q:'Why did [NAME] add more flour?',a:'Because the batter was too runny',distractors:['Because it was too dry','Because it tasted salty','Because the oven was cold']} },
      { feeling:'happy',
        want:'wanted to pick the ripest tomatoes for a family salad',
        trigger:'walked through the garden rows looking for red and round',
        problem:'many tomatoes were still hard and green',
        help:'a wise gardener showed how to spot the ripe ones',
        solution:'gathered a basket of juicy red tomatoes for dinner',
        lesson:'a little know-how helps you make a good choice',
        mainIdea:'learns to pick ripe food from the garden',
        detail:'Ripe tomatoes are soft, red, and smell sweet.',
        extra:'The salad was the best part of dinner.',
        vocab:{word:'ripe',sentence:'A ripe tomato is ready to eat, soft and bright red.',meaning:'grown and ready to eat',distractors:['still growing','already rotten','frozen hard']},
        titles:['Ripe and Red','[NAME] in the Garden','Tomato Time'],
        why:{q:'How did [NAME] know which tomatoes to pick?',a:'A gardener showed how to spot ripe ones',distractors:['[NAME] guessed at random','The tomatoes glowed','A bird picked them']} },
      { feeling:'happy',
        want:'wanted to make a fresh pot of soup for a sick neighbor',
        trigger:'chopped carrots, celery, and onions on the kitchen counter',
        problem:'the soup tasted watery and needed something more',
        help:'a grandparent suggested a pinch of salt and a few fresh herbs',
        solution:'simmered the soup until it tasted warm, rich, and just right',
        lesson:'small adjustments can turn an okay dish into a great one',
        mainIdea:'makes soup for a neighbor who is feeling sick',
        detail:'A warm bowl of soup can help someone feel cared for.',
        extra:'The neighbor said it was the best soup they had ever tasted.',
        vocab:{word:'simmered',sentence:'The soup simmered gently, bubbling slowly on low heat.',meaning:'cooked slowly at a low heat',distractors:['froze solid in the freezer','was eaten raw and cold','was thrown away quickly']},
        titles:['Soup for a Neighbor','[NAME] Cooks with Care','A Warm Bowl'],
        why:{q:'How did [NAME] fix the watery soup?',a:'Added a pinch of salt and fresh herbs',distractors:['Added more water','Cooked it for one minute only','Put it in the freezer']} },
      { feeling:'proud',
        want:'wanted to set up a lemonade stand on the hottest day of summer',
        trigger:'squeezed fresh lemons into a big pitcher of cold water',
        problem:'the lemonade tasted much too sour for most customers',
        help:'a kind neighbor suggested stirring in a little extra sugar',
        solution:'mixed in just the right amount and sold out by lunchtime',
        lesson:'listening to feedback can help you improve your work',
        mainIdea:'fixes a recipe after listening to a neighbor\'s advice',
        detail:'Lemonade needs a balance of sour lemons and sweet sugar.',
        extra:'[NAME] saved up the earnings for a new bike.',
        vocab:{word:'sour',sentence:'The lemonade tasted sour, sharp and tangy on the tongue.',meaning:'having a sharp, tangy taste',distractors:['very sweet and syrupy','warm and cozy','soft and fluffy']},
        titles:['The Lemonade Stand','[NAME]\'s Sweet Fix','Sold Out by Lunch'],
        why:{q:'Why didn\'t people like the lemonade at first?',a:'It tasted much too sour',distractors:['It was too cold','It was the wrong color','There was not enough of it']} },
    ],
  },
  transportation: {
    heroes:[{name:'Toot',kind:'little train'},{name:'Bea',kind:'school bus'},{name:'Sky',kind:'small plane'},{name:'Finn',kind:'kid'}],
    settings:[{prose:'on a winding country railway',label:'On the railway'},{prose:'along a busy city road',label:'On the road'},{prose:'at a small grassy airfield',label:'At the airfield'}],
    episodes:[
      { feeling:'proud',
        want:'wanted to carry the mail over the hill to the next town',
        trigger:'chugged up the track with a heavy load of letters',
        problem:'the hill was steep and the wheels began to slow',
        help:'a friendly engine gave a gentle push from behind',
        solution:'rolled over the top and coasted down to the town',
        lesson:'a push from a friend helps you over the hump',
        mainIdea:'carries the mail over a steep hill',
        detail:'The mailbag was stuffed full of letters.',
        extra:'The town cheered as the mail arrived on time.',
        vocab:{word:'steep',sentence:'The steep hill went sharply up, hard to climb.',meaning:'rising sharply and high',distractors:['flat and low','soft and round','wet and muddy']},
        titles:['Over the Hill','[NAME] Carries the Mail','The Big Climb'],
        why:{q:'How did [NAME] get over the hill?',a:'A friendly engine gave a push',distractors:['It flew over','The hill moved away','[NAME] used a balloon']} },
      { feeling:'excited',
        want:'wanted to take the children to school on a foggy morning',
        trigger:'rolled down the street with headlights glowing bright',
        problem:'the fog was so thick the next stop was hard to see',
        help:'a crossing guard waved a bright lantern at each corner',
        solution:'reached every stop safely and got everyone to school',
        lesson:'going slow and careful keeps everyone safe',
        mainIdea:'gets children to school safely in the fog',
        detail:'The fog made the whole street look gray.',
        extra:'The children waved thank you out the windows.',
        vocab:{word:'thick',sentence:'The fog was so thick it was hard to see very far.',meaning:'heavy and hard to see through',distractors:['thin and clear','warm and dry','loud and fast']},
        titles:['The Foggy Morning','[NAME] on the Road','Safe to School'],
        why:{q:'Why was it hard to see the next stop?',a:'Because the fog was very thick',distractors:['Because it was nighttime','Because the lights broke','Because it was snowing']} },
      { feeling:'proud',
        want:'wanted to fly a banner over the town for the big summer festival',
        trigger:'took off from the small airfield with the banner trailing behind',
        problem:'a sudden gust of wind twisted the banner into a tangle',
        help:'gently dipping a wing helped straighten the banner back out',
        solution:'flew a smooth, steady loop with the banner flying straight and proud',
        lesson:'a calm, steady response can fix a sudden surprise',
        mainIdea:'fixes a tangled banner while flying over the festival',
        detail:'Banners flown behind small planes can be seen from far below.',
        extra:'The whole town looked up and cheered at the bright banner.',
        vocab:{word:'tangle',sentence:'The wind twisted the banner into a tangle of cloth and rope.',meaning:'a messy, twisted knot',distractors:['a neat, flat sheet','a loud crashing sound','a bright shining light']},
        titles:['The Festival Banner','[NAME] in the Sky','A Steady Loop'],
        why:{q:'How did [NAME] fix the tangled banner?',a:'By dipping a wing to straighten it out',distractors:['By landing right away','By flying upside down','By cutting the banner loose']} },
      { feeling:'grateful',
        want:'wanted to get every passenger to the train station before it left',
        trigger:'rolled down the road picking up passengers stop by stop',
        problem:'traffic was backed up much further than expected',
        help:'a police officer cleared a path through the busy intersection',
        solution:'rolled through just in time for everyone to catch the train',
        lesson:'a little help can turn a close call into a happy ending',
        mainIdea:'gets passengers to the station despite heavy traffic',
        detail:'Buses follow a schedule so passengers know when to expect them.',
        extra:'Every passenger thanked [NAME] while waving from the platform.',
        vocab:{word:'intersection',sentence:'The intersection was where two busy streets crossed each other.',meaning:'a place where roads cross',distractors:['a kind of bridge','a small park','a quiet alley']},
        titles:['Racing the Clock','[NAME] Beats Traffic','Just in Time for the Train'],
        why:{q:'How did [NAME] get through the traffic in time?',a:'A police officer cleared a path through it',distractors:['The traffic disappeared','[NAME] flew over it','Passengers walked instead']} },
    ],
  },
  seasons: {
    heroes:[{name:'Maple',kind:'kid'},{name:'Sol',kind:'child'},{name:'Wren',kind:'girl'},{name:'Bo',kind:'boy'}],
    settings:[{prose:'in a backyard full of trees',label:'In the backyard'},{prose:'at a park by the pond',label:'At the park'},{prose:'on a quiet country lane',label:'On a country lane'}],
    episodes:[
      { feeling:'joyful',
        want:'wanted to rake the autumn leaves into one giant pile',
        trigger:'swept the red and gold leaves across the whole yard',
        problem:'a gust of wind scattered the leaves everywhere',
        help:'a sibling grabbed a second rake and joined right in',
        solution:'built a huge crunchy pile and jumped right into it',
        lesson:'a chore turns to fun when you share it',
        mainIdea:'rakes autumn leaves and plays in them',
        detail:'In autumn, leaves turn red, orange, and gold.',
        extra:'They jumped in the pile until sunset.',
        vocab:{word:'scattered',sentence:'The wind scattered the leaves, spreading them all around.',meaning:'spread all around',distractors:['stacked them neatly','glued them down','hid them away']},
        titles:['The Leaf Pile','Autumn Fun','[NAME] and the Wind'],
        why:{q:'Why did the leaves go everywhere?',a:'Because a gust of wind scattered them',distractors:['Because it was summer','Because they melted','Because a dog ate them']} },
      { feeling:'happy',
        want:'wanted to build the very first snowman of winter',
        trigger:'rolled three big snowballs across the frosty yard',
        problem:'the top ball kept rolling off and breaking apart',
        help:'a friend packed the snow tight so it would stick',
        solution:'stacked the snowman tall and added a carrot nose',
        lesson:'patience and a friend make the work worthwhile',
        mainIdea:'builds a snowman with a friend in winter',
        detail:'In winter, soft snow covers everything in white.',
        extra:'They named the snowman and waved goodnight.',
        vocab:{word:'frosty',sentence:'The frosty yard was cold and covered in white ice.',meaning:'cold and icy',distractors:['warm and sunny','dry and dusty','green and grassy']},
        titles:['The First Snowman','Winter Fun','[NAME] in the Snow'],
        why:{q:'Why did the top ball keep falling?',a:'Because the snow was not packed tight',distractors:['Because it was too hot','Because it was raining','Because it was nighttime']} },
      { feeling:'excited',
        want:'wanted to spot the very first flower of spring in the backyard',
        trigger:'checked the garden every morning after the long, gray winter',
        problem:'the ground still looked bare and brown for many weeks',
        help:'warmer days and gentle rain slowly woke up the sleepy soil',
        solution:'spotted a tiny green shoot poking up at last',
        lesson:'good things take time, even when waiting feels hard',
        mainIdea:'watches patiently for the first sign of spring',
        detail:'Plants rest underground all winter before growing again in spring.',
        extra:'[NAME] watered the little shoot every single day after that.',
        vocab:{word:'shoot',sentence:'A tiny green shoot is the very first part of a new plant to grow.',meaning:'a new, young part of a plant',distractors:['a loud sound','a kind of bird','a heavy rock']},
        titles:['The First Sign of Spring','[NAME] Watches and Waits','A Tiny Green Shoot'],
        why:{q:'Why did the garden look bare for so long?',a:'Plants rest underground through the winter',distractors:['The seeds were lost','It never rained at all','The garden was too small']} },
      { feeling:'happy',
        want:'wanted to find the coolest, shadiest spot on the hottest summer day',
        trigger:'wandered the whole backyard looking for relief from the heat',
        problem:'every spot in the sun felt just as hot as the last',
        help:'a tall, leafy tree offered a wide patch of cool shade',
        solution:'spread out a blanket under the tree and relaxed all afternoon',
        lesson:'sometimes the best plan is to slow down and find some shade',
        mainIdea:'finds a cool place to relax on a hot summer day',
        detail:'Shade from a tree can feel many degrees cooler than direct sun.',
        extra:'[NAME] fell asleep listening to leaves rustle overhead.',
        vocab:{word:'relief',sentence:'The cool shade brought relief from the hot summer sun.',meaning:'a feeling of comfort after discomfort',distractors:['a feeling of being lost','a loud, sudden noise','a sharp, sudden pain']},
        titles:['Finding the Shade','[NAME]\'s Cool Spot','A Summer Afternoon'],
        why:{q:'How did [NAME] finally cool off?',a:'By relaxing in the shade under a tree',distractors:['By staying in the hot sun','By running very fast','By going inside all day']} },
    ],
  },
  plants: {
    heroes:[{name:'Fern',kind:'kid'},{name:'Basil',kind:'child'},{name:'Posy',kind:'girl'},{name:'Reed',kind:'boy'}],
    settings:[{prose:'in a green vegetable garden',label:'In the garden'},{prose:'on a sunny windowsill',label:'On the windowsill'},{prose:'at a community plant patch',label:'At the plant patch'}],
    episodes:[
      { feeling:'proud',
        want:'wanted to grow a sunflower taller than anyone else\'s',
        trigger:'planted a little seed in a pot of dark, rich soil',
        problem:'days went by and nothing seemed to be happening',
        help:'a wise neighbor explained that seeds grow slowly underground',
        solution:'kept watering until a green sprout pushed up at last',
        lesson:'good things grow for those who wait and care',
        mainIdea:'grows a plant with patience and care',
        detail:'A seed needs water, sun, and time to grow.',
        extra:'By summer the sunflower was taller than [NAME].',
        vocab:{word:'sprout',sentence:'A green sprout, the tiny first part of a plant, popped up.',meaning:'a tiny new plant',distractors:['a dead leaf','a big rock','a fat worm']},
        titles:['The Tall Sunflower','[NAME]\'s Seed','Growing Up'],
        why:{q:'Why did nothing seem to happen at first?',a:'Because seeds grow slowly underground',distractors:['Because the seed was broken','Because it was winter','Because a bird took it']} },
      { feeling:'grateful',
        want:'wanted to save a droopy plant that had stopped growing',
        trigger:'noticed the leaves turning pale and curling down',
        problem:'no one was sure what the little plant needed',
        help:'a gardener checked the soil and found it bone dry',
        solution:'gave the plant a deep drink and moved it to the sun',
        lesson:'paying close attention helps you solve a problem',
        mainIdea:'figures out how to help a sick plant',
        detail:'Plants need water and light to stay healthy.',
        extra:'In a week the leaves stood up green and strong.',
        vocab:{word:'droopy',sentence:'The droopy plant hung down, weak and tired-looking.',meaning:'hanging down weakly',distractors:['standing up strong','bright and shiny','tall and stiff']},
        titles:['Saving the Plant','[NAME] the Helper','Green Again'],
        why:{q:'What was wrong with the plant?',a:'The soil was bone dry and it needed water',distractors:['It had too much water','It was too cold','It needed a bigger pot']} },
      { feeling:'proud',
        want:'wanted to grow a row of carrots for the very first time',
        trigger:'planted tiny carrot seeds in straight, careful rows',
        problem:'weeds grew faster than the carrots and crowded them out',
        help:'a neighbor showed how to gently pull weeds without hurting the carrots',
        solution:'cleared the weeds and watched the carrot tops grow tall and green',
        lesson:'clearing away the trouble gives good things room to grow',
        mainIdea:'learns to garden by clearing away weeds',
        detail:'Weeds can take water and sunlight away from other plants.',
        extra:'[NAME] pulled up a crunchy, orange carrot at harvest time.',
        vocab:{word:'weeds',sentence:'Weeds are unwanted plants that crowd out the ones you want to grow.',meaning:'unwanted plants that grow where they are not wanted',distractors:['ripe vegetables','garden tools','bright flowers']},
        titles:['The Carrot Row','[NAME] Clears the Weeds','Room to Grow'],
        why:{q:'Why were the carrots having trouble growing?',a:'Weeds were crowding them out',distractors:['There was too much rain','The seeds were planted upside down','It was too cold outside']} },
      { feeling:'joyful',
        want:'wanted to share extra seedlings with everyone on the street',
        trigger:'noticed far too many seedlings sprouting in just one small pot',
        problem:'the crowded pot left no room for any of them to grow well',
        help:'a neighbor offered empty pots so seedlings could be spread out',
        solution:'gave a little seedling to every neighbor who wanted one',
        lesson:'sharing extra can help everyone grow something good',
        mainIdea:'shares extra seedlings with neighbors',
        detail:'A seedling is a young plant that has just begun to grow.',
        extra:'Soon the whole street had cheerful little gardens.',
        vocab:{word:'seedlings',sentence:'The seedlings were tiny young plants just starting to grow.',meaning:'young plants grown from seeds',distractors:['fully grown trees','dry, empty pots','small garden tools']},
        titles:['Sharing the Seedlings','[NAME] Spreads the Green','A Street Full of Gardens'],
        why:{q:'Why did [NAME] share the seedlings with neighbors?',a:'The crowded pot left no room for them to grow',distractors:['The seedlings were dying anyway','[NAME] did not want any plants','It was a neighborhood rule']} },
    ],
  },
  mysteries: {
    heroes:[{name:'Detective Dot',kind:'kid sleuth'},{name:'Sam',kind:'young detective'},{name:'Iris',kind:'girl'},{name:'Theo',kind:'boy'}],
    settings:[{prose:'in a quiet old library',label:'In the library'},{prose:'around a cozy neighborhood',label:'In the neighborhood'},{prose:'inside a curious little museum',label:'At the museum'}],
    episodes:[
      { feeling:'proud',
        want:'wanted to find out who kept leaving tiny footprints in the hall',
        trigger:'followed a trail of little muddy prints down the corridor',
        problem:'the prints stopped right in front of a closed door',
        help:'a friend remembered seeing the class hamster get loose',
        solution:'opened the door and found the hamster hiding inside',
        lesson:'looking closely at clues solves the puzzle',
        mainIdea:'follows clues to solve a small mystery',
        detail:'The footprints were no bigger than a coin.',
        extra:'The hamster was safe and ready for a snack.',
        vocab:{word:'clues',sentence:'The footprints were clues, hints that help solve a mystery.',meaning:'hints that help solve a puzzle',distractors:['big mistakes','funny jokes','heavy boxes']},
        titles:['The Tiny Footprints','[NAME] Solves It','The Missing Hamster'],
        why:{q:'Who was leaving the footprints?',a:'The class hamster that had gotten loose',distractors:['A tiny ghost','A robber','A puddle of rain']} },
      { feeling:'joyful',
        want:'wanted to find the missing piece of the museum puzzle',
        trigger:'searched every shelf for the one lost puzzle piece',
        problem:'the piece was nowhere to be seen all afternoon',
        help:'a guard remembered sweeping something under a bench',
        solution:'peeked under the bench and found the missing piece',
        lesson:'a calm, careful search beats a frantic one',
        mainIdea:'searches carefully to find a lost piece',
        detail:'The puzzle showed a giant blue whale.',
        extra:'The finished puzzle went on display for all to see.',
        vocab:{word:'searched',sentence:'[NAME] searched, looking everywhere for the lost piece.',meaning:'looked hard for something',distractors:['threw it away','ran outside','took a nap']},
        titles:['The Missing Piece','[NAME] at the Museum','Found It!'],
        why:{q:'Where was the missing piece?',a:'Under a bench where it had been swept',distractors:['Inside the whale tank','In [NAME]\'s pocket','On the moon']} },
      { feeling:'proud',
        want:'wanted to find out who kept leaving chalk drawings on the sidewalk',
        trigger:'noticed a brand-new colorful drawing every single morning',
        problem:'no one in the neighborhood seemed to know who was drawing them',
        help:'an early wake-up call let [NAME] spot the artist in the act',
        solution:'discovered it was a kind neighbor brightening everyone\'s morning',
        lesson:'a little curiosity can uncover a wonderful surprise',
        mainIdea:'solves the mystery of the sidewalk drawings',
        detail:'Chalk drawings wash away easily, so new ones can appear often.',
        extra:'The neighborhood thanked the artist with a chalk drawing of their own.',
        vocab:{word:'uncover',sentence:'Waking up early helped [NAME] uncover who was really behind the drawings.',meaning:'to find out something hidden',distractors:['to hide something away','to forget about something','to draw a picture']},
        titles:['The Chalk Mystery','[NAME] Wakes Up Early','A Colorful Surprise'],
        why:{q:'How did [NAME] solve the mystery?',a:'By waking up early to spot the artist',distractors:['By asking a fortune teller','By giving up the search','By moving to a new street']} },
      { feeling:'joyful',
        want:'wanted to figure out who returned a lost wallet to the front desk',
        trigger:'noticed a wallet sitting at the desk with no note attached',
        problem:'nobody at the desk remembered seeing who dropped it off',
        help:'a security camera recording showed a quick glimpse of a kind stranger',
        solution:'tracked down the stranger and learned they return lost items often',
        lesson:'good deeds do not need a name attached to count',
        mainIdea:'discovers who returned a lost wallet',
        detail:'Security cameras can record what happens even when no one is watching directly.',
        extra:'[NAME] decided to start returning lost items, too.',
        vocab:{word:'glimpse',sentence:'The recording gave only a quick glimpse of the kind stranger.',meaning:'a brief, quick look at something',distractors:['a long, slow look','a loud, clear sound','a written note']},
        titles:['The Returned Wallet','[NAME] Finds the Helper','A Kind Stranger'],
        why:{q:'How did [NAME] learn who returned the wallet?',a:'A security camera recording showed a glimpse of them',distractors:['The stranger left a name tag','A note explained everything','No one ever found out']} },
    ],
  },
  'school adventures': {
    heroes:[{name:'Ana',kind:'student'},{name:'Jamal',kind:'kid'},{name:'Lin',kind:'girl'},{name:'Theo',kind:'boy'}],
    settings:[{prose:'in a busy classroom',label:'In the classroom'},{prose:'out on the playground',label:'On the playground'},{prose:'in the school art room',label:'In the art room'}],
    episodes:[
      { feeling:'proud',
        want:'wanted to win the class spelling game on Friday',
        trigger:'practiced the tricky words over and over all week',
        problem:'one long word kept getting jumbled up',
        help:'a classmate shared a clever trick to remember it',
        solution:'spelled the word right and grinned from ear to ear',
        lesson:'a smart tip and some practice go a long way',
        mainIdea:'practices hard to do well at school',
        detail:'The tricky word had a silent letter.',
        extra:'The whole class clapped for [NAME].',
        vocab:{word:'jumbled',sentence:'The letters got jumbled, all mixed up in the wrong order.',meaning:'mixed up in a messy way',distractors:['lined up neatly','spelled correctly','painted bright']},
        titles:['The Spelling Game','[NAME]\'s Tricky Word','Friday\'s Win'],
        why:{q:'How did [NAME] finally spell the word?',a:'A classmate shared a trick to remember it',distractors:['[NAME] guessed','The word changed','A teacher said it aloud']} },
      { feeling:'happy',
        want:'wanted to paint a mural for the school hallway',
        trigger:'sketched a big bright design on the long blank wall',
        problem:'there was far too much wall for one painter alone',
        help:'the whole class grabbed brushes and pitched in',
        solution:'painted a colorful mural that filled the hallway',
        lesson:'a big dream comes true when everyone helps',
        mainIdea:'creates a mural with the whole class',
        detail:'The mural showed a garden full of birds.',
        extra:'Every student signed a corner of the mural.',
        vocab:{word:'mural',sentence:'A mural is a big painting made right on a wall.',meaning:'a big painting on a wall',distractors:['a small photo','a paper note','a clay pot']},
        titles:['The Big Mural','[NAME]\'s Wall','Color the Hallway'],
        why:{q:'Why did [NAME] need the whole class?',a:'Because the wall was too big for one painter',distractors:['Because the paint ran out','Because it was raining','Because the bell rang']} },
      { feeling:'proud',
        want:'wanted to build the best volcano for the science fair',
        trigger:'mixed baking soda and vinegar inside a small clay mountain',
        problem:'the first try fizzled out with barely a bubble',
        help:'a teacher suggested using a little more vinegar for a bigger reaction',
        solution:'mixed it again and watched a bubbly eruption spill down the sides',
        lesson:'trying again with a small change can lead to a big success',
        mainIdea:'fixes a science project after a first try fails',
        detail:'Baking soda and vinegar react together to make lots of bubbles.',
        extra:'[NAME] won a ribbon for the most exciting project at the fair.',
        vocab:{word:'reaction',sentence:'Adding more vinegar created a bigger, bubblier reaction.',meaning:'what happens when two things mix or interact',distractors:['a kind of plant','a loud bell','a school subject']},
        titles:['The Science Fair Volcano','[NAME]\'s Big Eruption','Try Again, Try Bigger'],
        why:{q:'Why did the second try work better?',a:'[NAME] used a little more vinegar',distractors:['The clay was a different color','It was a sunny day','A friend blew on it']} },
      { feeling:'happy',
        want:'wanted to find a missing homework page before the bell rang',
        trigger:'searched through a backpack stuffed with books and papers',
        problem:'minutes were ticking by with no sign of the missing page',
        help:'a classmate remembered seeing it slip into a different folder',
        solution:'found the page tucked safely inside the right folder',
        lesson:'staying calm and asking for help can solve a stressful problem',
        mainIdea:'finds missing homework with help from a classmate',
        detail:'Keeping papers organized in folders can help them stay easy to find.',
        extra:'[NAME] turned in the homework with a minute to spare.',
        vocab:{word:'organized',sentence:'Papers that are organized into folders are much easier to find.',meaning:'arranged in a neat, orderly way',distractors:['scattered everywhere','torn into pieces','hidden out of sight']},
        titles:['The Missing Page','[NAME] Finds It','Just Before the Bell'],
        why:{q:'How was the missing homework finally found?',a:'A classmate remembered where it had slipped',distractors:['It was never found','A teacher had taken it','It fell out of a window']} },
    ],
  },
};

// flatten pools used for distractors across all topics
const HERO_POOL = [];
const SETTING_LABELS = [];
Object.values(FICTION_PACKS).forEach(p=>{
  p.heroes.forEach(h=> HERO_POOL.push(h));
  p.settings.forEach(s=> SETTING_LABELS.push(s.label));
});

Object.assign(window, { FICTION_PACKS, HERO_POOL, SETTING_LABELS });

