// ====== OFFLINE NON-FICTION CONTENT PACKS (all topics) ======
// Each subject carries facts (some with a built-in question), one inference,
// and one vocab word, so the comprehension questions always have correct answers.

const NONFICTION_PACKS = {
  animals: {
    subjects:[
      { label:'Penguins',
        titles:['All About Penguins','Penguin Facts','Birds of the Ice'],
        intro:'Penguins are birds that live where it is cold and icy.',
        theme:'Penguins are birds that swim instead of fly and stay warm together.',
        closer:'Penguins show us that animals find clever ways to live in hard places.',
        facts:[
          { text:'Even though penguins are birds, they cannot fly.', q:'Why are penguins unusual birds?', a:'They cannot fly', distractors:['They have no feathers','They live in deserts','They sleep all winter'] },
          { text:'Penguins are amazing swimmers and use their wings like flippers.', q:'How do penguins use their wings?', a:'Like flippers for swimming', distractors:['To fly very high','To dig deep holes','To carry their eggs'] },
          { text:'Thick feathers and a layer of fat keep penguins warm in the cold.' },
          { text:'Many penguins huddle together in big groups to share their warmth.', q:'Why do penguins huddle together?', a:'To share warmth', distractors:['To play games','To take naps','To hide their food'] },
          { text:'Penguins eat fish and squid that they catch in the sea.' },
          { text:'A baby penguin is called a chick and has soft fluffy feathers.' },
        ],
        inference:{ q:'Why might a penguin be safer in a group than alone?', a:'A group shares warmth and watches for danger', distractors:['A group can fly away','One penguin eats more','Alone, it swims faster'] },
        vocab:{ word:'huddle', meaning:'to crowd close together', distractors:['to swim away fast','to fall asleep','to build a nest'] } },
      { label:'Elephants',
        titles:['All About Elephants','Elephant Facts','The Biggest Land Animal'],
        intro:'Elephants are the largest animals that live on land.',
        theme:'Elephants are huge, smart animals that use their trunks for almost everything.',
        closer:'Elephants remind us that even the biggest animals can be gentle and caring.',
        facts:[
          { text:'An elephant\'s trunk is strong enough to lift a log but gentle enough to pick a single leaf.', q:'What can an elephant do with its trunk?', a:'Lift a log and pick a single leaf', distractors:['Fly short distances','See in the dark','Make fire'] },
          { text:'Elephants use their trunks to drink water, grab food, and even give themselves a dust bath.' },
          { text:'Elephants live together in family groups led by the oldest female.', q:'Who leads an elephant family?', a:'The oldest female', distractors:['The biggest male','The youngest baby','No one at all'] },
          { text:'Big floppy ears help elephants stay cool in the hot sun.', q:'How do big ears help an elephant?', a:'They help it stay cool', distractors:['They help it fly','They help it dig','They help it swim'] },
          { text:'Elephants are very smart and can remember places and other elephants for years.' },
          { text:'A baby elephant is called a calf and can weigh as much as a grown person.' },
        ],
        inference:{ q:'Why is a good memory helpful to an elephant?', a:'It can remember where to find water and food', distractors:['It can grow bigger ears','It can learn to fly','It needs to eat less'] },
        vocab:{ word:'trunk', meaning:'an elephant\'s long, bendy nose', distractors:['a kind of tree','a big suitcase','a heavy foot'] } },
    ],
  },
  space: {
    subjects:[
      { label:'The Moon',
        titles:['All About the Moon','Moon Facts','Our Night Light'],
        intro:'The Moon is the bright round object we see in the night sky.',
        theme:'The Moon circles our planet and shines with light from the Sun.',
        closer:'The Moon is our closest neighbor in space, and people have even walked on it.',
        facts:[
          { text:'The Moon does not make its own light; it reflects light from the Sun.', q:'Where does the Moon\'s light come from?', a:'It reflects light from the Sun', distractors:['It makes its own fire','It glows from inside','It borrows from stars'] },
          { text:'The Moon travels all the way around Earth about once a month.', q:'How long does the Moon take to circle Earth?', a:'About one month', distractors:['About one day','About one year','About one hour'] },
          { text:'The Moon is covered in dust and round dents called craters.' },
          { text:'There is no air to breathe on the Moon.' },
          { text:'Astronauts first walked on the Moon many years ago and left footprints in the dust.', q:'What did astronauts leave on the Moon?', a:'Footprints in the dust', distractors:['Tall green trees','Big blue lakes','Flying birds'] },
          { text:'The Moon looks like it changes shape, from a thin sliver to a full circle.' },
        ],
        inference:{ q:'Why can\'t people breathe on the Moon without help?', a:'Because the Moon has no air', distractors:['Because it is too bright','Because it spins fast','Because it is made of cheese'] },
        vocab:{ word:'craters', meaning:'round dents in the ground', distractors:['tall mountains','deep oceans','bright stars'] } },
      { label:'Mars',
        titles:['All About Mars','Mars Facts','The Red Planet'],
        intro:'Mars is a planet often called the Red Planet.',
        theme:'Mars is a cold, dusty, red planet that scientists love to explore.',
        closer:'Robots called rovers drive across Mars to learn what the planet is like.',
        facts:[
          { text:'Mars looks red because its soil is full of rusty iron dust.', q:'Why does Mars look red?', a:'Its soil is full of rusty dust', distractors:['It is on fire','It is close to the Sun','It is covered in flowers'] },
          { text:'Mars is much colder than Earth, even on a sunny day.' },
          { text:'Mars has the tallest volcano of any planet we know.', q:'What record does Mars hold?', a:'It has the tallest volcano', distractors:['The most water','The brightest light','The loudest storms'] },
          { text:'Robots called rovers drive across Mars and send back pictures.', q:'What explores the surface of Mars?', a:'Robots called rovers', distractors:['Trained dogs','Tiny boats','Flying fish'] },
          { text:'Mars has two tiny moons that circle around it.' },
          { text:'A day on Mars is just a little longer than a day on Earth.' },
        ],
        inference:{ q:'Why do scientists send rovers instead of people to Mars?', a:'Mars is far away and hard for people to live on', distractors:['Rovers are cheaper to feed','People do not like Mars','Rovers can fly there faster'] },
        vocab:{ word:'rover', meaning:'a robot that drives and explores', distractors:['a kind of star','a space blanket','a moon rock'] } },
    ],
  },
  ocean: {
    subjects:[
      { label:'Blue Whales',
        titles:['All About Blue Whales','Whale Facts','The Biggest Animal'],
        intro:'The blue whale is the largest animal that has ever lived.',
        theme:'Blue whales are gigantic ocean animals that eat tiny food.',
        closer:'It is amazing that the biggest animal on Earth lives on some of the smallest food.',
        facts:[
          { text:'A blue whale is bigger than any dinosaur that ever lived.', q:'How does a blue whale compare to dinosaurs?', a:'It is bigger than any dinosaur', distractors:['It is much smaller','It is exactly the same','It lived with dinosaurs'] },
          { text:'Blue whales eat tiny shrimp-like animals called krill.', q:'What do blue whales eat?', a:'Tiny animals called krill', distractors:['Large sharks','Sea plants','Other whales'] },
          { text:'A blue whale\'s heart is about as big as a small car.', q:'How big is a blue whale\'s heart?', a:'About as big as a small car', distractors:['As big as a coin','As big as a shoe','As big as a pea'] },
          { text:'Blue whales are mammals, so they come to the surface to breathe air.' },
          { text:'A baby blue whale, called a calf, drinks lots of milk and grows very fast.' },
          { text:'Blue whales can make sounds so loud that other whales hear them far away.' },
        ],
        inference:{ q:'Why must a blue whale swim up to the surface?', a:'Because it is a mammal and needs to breathe air', distractors:['Because it is afraid of the deep','Because the food floats on top','Because it cannot swim down'] },
        vocab:{ word:'krill', meaning:'tiny shrimp-like sea animals', distractors:['large hungry sharks','green ocean plants','small sandy rocks'] } },
      { label:'Coral Reefs',
        titles:['All About Coral Reefs','Reef Facts','Cities Under the Sea'],
        intro:'A coral reef is a colorful home for thousands of sea animals.',
        theme:'Coral reefs are busy underwater homes built by tiny living things.',
        closer:'Coral reefs are like busy cities, full of life under the waves.',
        facts:[
          { text:'Coral may look like rock, but it is made by tiny living animals.', q:'What makes a coral reef?', a:'Tiny living animals', distractors:['Melted glass','Old shells only','Falling stars'] },
          { text:'Reefs give food and shelter to fish, crabs, turtles, and many more.', q:'What do reefs give to sea animals?', a:'Food and shelter', distractors:['A place to fly','Warm blankets','Fresh water'] },
          { text:'Coral reefs grow very slowly, only a little bit each year.' },
          { text:'Reefs come in bright colors like orange, pink, and purple.' },
          { text:'Many medicines and foods come from animals that live on reefs.' },
          { text:'Warm, clean water helps a coral reef stay healthy.', q:'What helps a reef stay healthy?', a:'Warm, clean water', distractors:['Cold, muddy water','Lots of trash','Total darkness'] },
        ],
        inference:{ q:'Why might losing a reef be bad for fish?', a:'The fish would lose their food and shelter', distractors:['The fish would get bigger','The water would turn red','The fish would learn to fly'] },
        vocab:{ word:'shelter', meaning:'a safe place to stay', distractors:['a kind of fish','a loud sound','a sandy beach'] } },
    ],
  },
  weather: {
    subjects:[
      { label:'Thunderstorms',
        titles:['All About Thunderstorms','Storm Facts','Lightning and Thunder'],
        intro:'A thunderstorm is a storm with lightning and thunder.',
        theme:'Thunderstorms bring lightning, thunder, and heavy rain from tall clouds.',
        closer:'Thunderstorms can be loud and exciting, but it is safest to watch from inside.',
        facts:[
          { text:'Lightning is a giant spark of electricity in the sky.', q:'What is lightning?', a:'A giant spark of electricity', distractors:['A falling star','A loud drum','A puff of smoke'] },
          { text:'Thunder is the loud sound that lightning makes.', q:'What makes the sound of thunder?', a:'Lightning', distractors:['The wind','The rain','The clouds bumping'] },
          { text:'You see lightning before you hear thunder because light travels faster than sound.', q:'Why do you see lightning before you hear thunder?', a:'Light travels faster than sound', distractors:['Thunder is shy','Lightning is louder','The rain blocks the sound'] },
          { text:'Thunderstorms grow inside tall, dark clouds.' },
          { text:'During a storm, the safest place to be is indoors.' },
          { text:'Heavy rain and strong wind often come with a thunderstorm.' },
        ],
        inference:{ q:'If you count seconds between lightning and thunder, what does it tell you?', a:'How far away the storm is', distractors:['How long the storm will last','How many clouds there are','What color the rain is'] },
        vocab:{ word:'electricity', meaning:'a kind of energy that can make a spark', distractors:['a type of cloud','a heavy rain','a warm wind'] } },
      { label:'Rainbows',
        titles:['All About Rainbows','Rainbow Facts','Colors in the Sky'],
        intro:'A rainbow is an arch of colors that appears in the sky.',
        theme:'Rainbows form when sunlight shines through raindrops.',
        closer:'A rainbow is sunlight and rain working together to paint the sky.',
        facts:[
          { text:'A rainbow appears when the Sun shines through tiny raindrops.', q:'What two things make a rainbow?', a:'Sunlight and raindrops', distractors:['Snow and wind','Fire and smoke','Stars and night'] },
          { text:'A rainbow has seven colors, from red on the outside to violet on the inside.', q:'How many colors are in a rainbow?', a:'Seven', distractors:['Three','Ten','One'] },
          { text:'Raindrops bend the sunlight and split it into many colors.' },
          { text:'You often see a rainbow right after it rains and the Sun comes out.', q:'When do you often see a rainbow?', a:'After it rains and the Sun comes out', distractors:['In the middle of the night','During a snowstorm','Deep underground'] },
          { text:'To see a rainbow, the Sun must be behind you.' },
          { text:'Sometimes you can see two rainbows at once, one above the other.' },
        ],
        inference:{ q:'Why can\'t you see a rainbow on a cloudy day with no Sun?', a:'A rainbow needs sunlight to form', distractors:['Rainbows only come at night','Clouds eat rainbows','Rainbows are too shy'] },
        vocab:{ word:'arch', meaning:'a curved shape, like a bridge', distractors:['a straight line','a round ball','a deep hole'] } },
    ],
  },
  friendship: {
    subjects:[
      { label:'Being a Good Friend',
        titles:['How to Be a Good Friend','Friendship Tips','Kindness Counts'],
        intro:'Being a good friend means caring about other people.',
        theme:'Good friends are kind, they listen, and they help each other.',
        closer:'Small acts of kindness each day help friendships grow strong.',
        facts:[
          { text:'A good friend listens carefully when you talk.', q:'What does a good friend do when you talk?', a:'Listens carefully', distractors:['Walks away','Talks over you','Falls asleep'] },
          { text:'Sharing and taking turns helps friends get along.', q:'What helps friends get along?', a:'Sharing and taking turns', distractors:['Keeping everything','Always being first','Never talking'] },
          { text:'Saying sorry when you make a mistake helps fix a friendship.', q:'What helps fix a friendship after a mistake?', a:'Saying sorry', distractors:['Running away','Blaming others','Staying mad'] },
          { text:'Good friends cheer for each other when something goes well.' },
          { text:'Including others so no one feels left out is a kind thing to do.' },
          { text:'Friends can disagree and still care about each other.' },
        ],
        inference:{ q:'Why might saying sorry help, even if it feels hard?', a:'It shows you care and helps fix hurt feelings', distractors:['It makes the other person mad','It ends the friendship','It means you win'] },
        vocab:{ word:'include', meaning:'to make someone part of the group', distractors:['to leave someone out','to run very fast','to stay quiet'] } },
      { label:'Working as a Team',
        titles:['Working Together','Teamwork Tips','Better Together'],
        intro:'A team is a group of people working toward the same goal.',
        theme:'Teams do better when everyone helps and shares the work.',
        closer:'When a team works together, a big job becomes much easier.',
        facts:[
          { text:'On a team, each person does a part of the job.', q:'How does a team share a job?', a:'Each person does a part', distractors:['One person does it all','No one helps','They take turns sleeping'] },
          { text:'Listening to teammates\' ideas helps the team make good choices.', q:'What helps a team make good choices?', a:'Listening to each other\'s ideas', distractors:['Ignoring everyone','Shouting the loudest','Working alone'] },
          { text:'Cheering for teammates helps everyone feel encouraged.' },
          { text:'When people help each other, a hard job gets easier.', q:'What happens when people help each other?', a:'A hard job gets easier', distractors:['The job takes longer','Nothing changes','The team gives up'] },
          { text:'Good teams are patient when someone is still learning.' },
          { text:'Saying thank you helps a team feel happy and close.' },
        ],
        inference:{ q:'Why might a team finish a big job faster than one person?', a:'Many people share the work', distractors:['One person is always faster','Teams never get tired','The job shrinks by itself'] },
        vocab:{ word:'encourage', meaning:'to give someone hope and cheer them on', distractors:['to slow someone down','to take a long rest','to make a mess'] } },
    ],
  },
  sports: {
    subjects:[
      { label:'Soccer',
        titles:['All About Soccer','Soccer Facts','The Beautiful Game'],
        intro:'Soccer is a game played by two teams with a round ball.',
        theme:'Soccer is a team game where players move a ball to score goals.',
        closer:'Soccer is one of the most popular games in the whole world.',
        facts:[
          { text:'In soccer, players try to kick the ball into the other team\'s goal.', q:'How do soccer players score?', a:'By kicking the ball into the goal', distractors:['By throwing the ball','By catching the ball','By hiding the ball'] },
          { text:'Players use their feet, head, and body, but not their hands.', q:'What body part can soccer players NOT use?', a:'Their hands', distractors:['Their feet','Their head','Their chest'] },
          { text:'Only the goalkeeper is allowed to use their hands.', q:'Who may use their hands in soccer?', a:'The goalkeeper', distractors:['Everyone','No one','The referee'] },
          { text:'Each team tries to score more goals than the other team.' },
          { text:'A soccer game is split into two halves with a rest in between.' },
          { text:'Soccer is played and watched by people all around the world.' },
        ],
        inference:{ q:'Why is passing the ball to teammates helpful in soccer?', a:'It helps the team move the ball and score', distractors:['It makes the game shorter','It tires out your own team','It is against the rules'] },
        vocab:{ word:'goalkeeper', meaning:'the player who guards the goal', distractors:['the player who keeps score','a kind of ball','the team coach'] } },
      { label:'Swimming',
        titles:['All About Swimming','Swimming Facts','Moving Through Water'],
        intro:'Swimming is the way people move themselves through water.',
        theme:'Swimming is great exercise that also helps keep you safe in water.',
        closer:'Learning to swim is a skill that can keep you safe your whole life.',
        facts:[
          { text:'When you swim, you use your arms and legs to push through the water.', q:'How do you move when you swim?', a:'You push with your arms and legs', distractors:['You flap like a bird','You roll like a ball','You float without moving'] },
          { text:'Taking a breath at the right time helps swimmers keep going.', q:'What helps swimmers keep going?', a:'Breathing at the right time', distractors:['Holding their breath the whole time','Closing both eyes','Swimming backward'] },
          { text:'Swimming is good exercise for your whole body.' },
          { text:'Knowing how to swim helps keep you safe near water.', q:'Why is knowing how to swim important?', a:'It helps keep you safe near water', distractors:['It makes you taller','It lets you breathe underwater','It helps you fly'] },
          { text:'There are different styles of swimming, like the backstroke and freestyle.' },
          { text:'It is always safest to swim where a grown-up can watch you.' },
        ],
        inference:{ q:'Why is it safest to swim where a grown-up is watching?', a:'They can help quickly if there is trouble', distractors:['They make the water warmer','They make you swim faster','They keep the pool clean'] },
        vocab:{ word:'stroke', meaning:'a style or way of swimming', distractors:['a kind of pool','a swim cap','a deep breath'] } },
    ],
  },
  dinosaurs: {
    subjects:[
      { label:'Tyrannosaurus Rex',
        titles:['All About T. rex','T. rex Facts','The King Dinosaur'],
        intro:'Tyrannosaurus rex, or T. rex, was a huge meat-eating dinosaur.',
        theme:'T. rex was a giant dinosaur with powerful jaws and tiny arms.',
        closer:'We learn about T. rex from the fossils it left behind long ago.',
        facts:[
          { text:'T. rex was one of the biggest meat-eating dinosaurs ever.', q:'What kind of food did T. rex eat?', a:'Meat', distractors:['Only leaves','Just berries','Sea plants'] },
          { text:'T. rex had a huge head and sharp teeth as long as bananas.', q:'How long were a T. rex\'s teeth?', a:'About as long as bananas', distractors:['As small as grains of rice','As long as a bus','Too tiny to see'] },
          { text:'Even though T. rex was huge, its arms were very short.', q:'What was surprising about T. rex\'s arms?', a:'They were very short', distractors:['They had feathers','They could fly','They had ten fingers'] },
          { text:'T. rex walked on two strong back legs.' },
          { text:'T. rex lived millions of years ago, long before people.' },
          { text:'We know about T. rex from fossils, the bones left in the ground.' },
        ],
        inference:{ q:'How can we learn about a dinosaur that lived so long ago?', a:'By studying the fossils it left behind', distractors:['By asking older people','By watching it today','By reading its diary'] },
        vocab:{ word:'fossils', meaning:'old bones or prints left in rock', distractors:['baby dinosaurs','large eggs','green plants'] } },
      { label:'Triceratops',
        titles:['All About Triceratops','Triceratops Facts','The Three-Horned Dinosaur'],
        intro:'Triceratops was a large dinosaur with three horns on its face.',
        theme:'Triceratops was a plant-eating dinosaur with horns and a bony frill.',
        closer:'Its horns and frill helped Triceratops stay safe from hungry hunters.',
        facts:[
          { text:'Triceratops had three horns: two long ones and one short one.', q:'How many horns did Triceratops have?', a:'Three', distractors:['One','Five','Ten'] },
          { text:'A big bony shield, called a frill, grew around its neck.', q:'What was the bony shield around its neck called?', a:'A frill', distractors:['A crown','A saddle','A shell'] },
          { text:'Triceratops ate plants, not meat.', q:'What did Triceratops eat?', a:'Plants', distractors:['Other dinosaurs','Fish','Rocks'] },
          { text:'Its horns could help protect it from meat-eating dinosaurs.' },
          { text:'Triceratops walked on four sturdy legs.' },
          { text:'Triceratops was about as big as a large truck.' },
        ],
        inference:{ q:'Why might Triceratops\'s horns have been useful?', a:'To protect it from hungry predators', distractors:['To help it fly','To dig for water','To climb tall trees'] },
        vocab:{ word:'frill', meaning:'a bony shield around the neck', distractors:['a sharp tooth','a long tail','a soft feather'] } },
    ],
  },
  'community helpers': {
    subjects:[
      { label:'Firefighters',
        titles:['All About Firefighters','Firefighter Facts','Helpers in Red'],
        intro:'Firefighters are helpers who keep people safe from fires.',
        theme:'Firefighters work as a team to put out fires and rescue people.',
        closer:'Firefighters are brave helpers who protect our whole town.',
        facts:[
          { text:'Firefighters use long hoses to spray water on fires.', q:'What do firefighters use to put out fires?', a:'Long hoses that spray water', distractors:['Big fans','Buckets of sand only','Loud sirens'] },
          { text:'They wear thick suits and helmets to stay safe from heat.', q:'Why do firefighters wear thick suits?', a:'To stay safe from heat', distractors:['To look funny','To swim better','To stay warm in snow'] },
          { text:'Firefighters also help in other emergencies, not just fires.' },
          { text:'A fire truck carries hoses, ladders, and tools to the fire.', q:'What does a fire truck carry?', a:'Hoses, ladders, and tools', distractors:['Toys and candy','Beds and pillows','Books and pencils'] },
          { text:'Firefighters teach families how to stay safe and make an escape plan.' },
          { text:'When the alarm rings, firefighters rush to the truck and hurry to help.' },
        ],
        inference:{ q:'Why is it important for firefighters to work as a team?', a:'A fire is dangerous, so they help each other stay safe', distractors:['Teams get more candy','One person could do it easier','Teams work slower'] },
        vocab:{ word:'emergency', meaning:'a sudden time when help is needed fast', distractors:['a quiet nap','a fun party','a long vacation'] } },
      { label:'Mail Carriers',
        titles:['All About Mail Carriers','Mail Carrier Facts','Helpers with Letters'],
        intro:'Mail carriers bring letters and packages to homes and shops.',
        theme:'Mail carriers deliver mail to the right place every day.',
        closer:'Thanks to mail carriers, your letters reach friends near and far.',
        facts:[
          { text:'A mail carrier reads the address to find the right home.', q:'How does a mail carrier find the right home?', a:'By reading the address', distractors:['By guessing','By calling out names','By following a dog'] },
          { text:'Letters and packages are sorted before they are delivered.', q:'What happens to mail before it is delivered?', a:'It is sorted', distractors:['It is painted','It is eaten','It is hidden'] },
          { text:'Mail carriers work in sun, rain, and snow to bring the mail.' },
          { text:'They carry mail in a bag or drive a small mail truck.', q:'How do mail carriers carry the mail?', a:'In a bag or a small truck', distractors:['On a big boat','In their pockets only','On a flying drone'] },
          { text:'A stamp on a letter shows that the mail has been paid for.' },
          { text:'Mail can travel across the whole country to reach you.' },
        ],
        inference:{ q:'Why is a clear address important on a letter?', a:'So the mail carrier knows exactly where to take it', distractors:['So it weighs less','So it can fly','So it costs nothing'] },
        vocab:{ word:'address', meaning:'the words that tell where someone lives', distractors:['a kind of stamp','a mail truck','a paper bag'] } },
    ],
  },
  camping: {
    subjects:[
      { label:'Camping Safety',
        titles:['Camping Safety','Staying Safe Outdoors','Camp Smart'],
        intro:'Camping is fun, and a few safe habits keep it that way.',
        theme:'Good campers plan ahead and follow safety rules outdoors.',
        closer:'When you camp safely, the outdoors is a wonderful place to explore.',
        facts:[
          { text:'Always camp with a grown-up and stay where they can see you.', q:'Who should you camp with?', a:'A grown-up', distractors:['No one at all','Only your pet','A stranger'] },
          { text:'Never touch a campfire, and let only grown-ups build and put it out.', q:'Who should handle the campfire?', a:'Only grown-ups', distractors:['Any child','The family dog','No one ever'] },
          { text:'Drink plenty of water so you do not get too thirsty.' },
          { text:'Stay on marked trails so you do not get lost.', q:'Why should you stay on marked trails?', a:'So you do not get lost', distractors:['To walk faster','To find candy','To stay clean'] },
          { text:'Keep your food packed away so it does not attract animals.' },
          { text:'Wearing the right clothes keeps you warm when it gets cold at night.' },
        ],
        inference:{ q:'Why might leaving food out be a problem when camping?', a:'It can attract wild animals to your camp', distractors:['It makes the food taste better','It helps you sleep','It keeps the camp clean'] },
        vocab:{ word:'trail', meaning:'a path to walk on outdoors', distractors:['a kind of tent','a campfire','a water bottle'] } },
      { label:'Reading a Trail Map',
        titles:['Reading a Trail Map','Finding Your Way','Map Skills'],
        intro:'A trail map is a drawing that helps you find your way outdoors.',
        theme:'A map uses pictures and symbols to show you where to go.',
        closer:'With a map and a little practice, you can find your way anywhere.',
        facts:[
          { text:'A map shows trails as lines you can follow.', q:'How does a map show a trail?', a:'As a line to follow', distractors:['As a big circle','As a tall tree','As a cloud'] },
          { text:'Small pictures, called symbols, stand for things like water or campsites.', q:'What do map symbols stand for?', a:'Real things like water or campsites', distractors:['Letters of your name','Numbers only','Nothing at all'] },
          { text:'A compass rose on the map shows which way is north.', q:'What does a compass rose show?', a:'Which way is north', distractors:['How far to walk','What time it is','How hot it is'] },
          { text:'Trail markers on signs and trees match the lines on the map.' },
          { text:'Maps help you guess how long a hike will take.' },
          { text:'Looking at the map often helps you stay on the right path.' },
        ],
        inference:{ q:'Why is it helpful to check the map often on a hike?', a:'To make sure you are still on the right path', distractors:['To make the hike longer','To rest your legs','To find a phone signal'] },
        vocab:{ word:'symbol', meaning:'a small picture that stands for something', distractors:['a long trail','a heavy backpack','a tall hill'] } },
    ],
  },
  insects: {
    subjects:[
      { label:'Honeybees',
        titles:['All About Honeybees','Honeybee Facts','Busy Bees'],
        intro:'Honeybees are insects that live together and make honey.',
        theme:'Honeybees work as a team to make honey and help plants grow.',
        closer:'Honeybees are tiny helpers that keep gardens and farms growing.',
        facts:[
          { text:'Honeybees collect a sweet juice from flowers called nectar.', q:'What do honeybees collect from flowers?', a:'Nectar', distractors:['Water','Sand','Leaves'] },
          { text:'Bees turn nectar into honey and store it in their hive.', q:'What do bees make from nectar?', a:'Honey', distractors:['Milk','Juice','Bread'] },
          { text:'When bees move from flower to flower, they help plants make seeds.', q:'How do bees help plants?', a:'They help plants make seeds', distractors:['They eat the weeds','They water the soil','They scare away birds'] },
          { text:'A bee colony has one queen and many worker bees.' },
          { text:'Bees can tell each other where flowers are by doing a little dance.' },
          { text:'Every bee in the hive has an important job to do.' },
        ],
        inference:{ q:'Why are honeybees important to farmers?', a:'They help plants grow food by moving from flower to flower', distractors:['They scare away the rain','They dig up the soil','They sell the honey'] },
        vocab:{ word:'hive', meaning:'the home where bees live together', distractors:['a single flower','a drop of honey','a garden tool'] } },
      { label:'Ants',
        titles:['All About Ants','Ant Facts','Tiny but Mighty'],
        intro:'Ants are small insects that live and work in big groups.',
        theme:'Ants work together in a colony to find food and build a home.',
        closer:'Ants show how working together helps a whole group survive.',
        facts:[
          { text:'Ants live in groups called colonies, sometimes with thousands of ants.', q:'What is a group of ants called?', a:'A colony', distractors:['A flock','A school','A pack'] },
          { text:'Ants are very strong and can carry food much heavier than themselves.', q:'What is surprising about how ants carry food?', a:'They carry things heavier than themselves', distractors:['They cannot lift anything','They eat as they carry','They fly the food home'] },
          { text:'Ants leave a scent trail so other ants can find food.', q:'How do ants help others find food?', a:'They leave a scent trail', distractors:['They shout loudly','They draw a map','They wave their legs'] },
          { text:'Each ant has a job, like finding food or caring for babies.' },
          { text:'Ants build their homes underground with many little tunnels.' },
          { text:'A queen ant lays the eggs for the whole colony.' },
        ],
        inference:{ q:'Why can ants do big jobs even though they are small?', a:'They work together as a team', distractors:['They are secretly huge','They never get tired','They use tiny machines'] },
        vocab:{ word:'colony', meaning:'a large group that lives together', distractors:['a single ant','a piece of food','an underground river'] } },
    ],
  },
  holidays: {
    subjects:[
      { label:'Holidays Around the World',
        titles:['Holidays Around the World','Celebrations Everywhere','How People Celebrate'],
        intro:'People all over the world celebrate special days called holidays.',
        theme:'Holidays bring people together to celebrate with food, music, and family.',
        closer:'No matter where they live, people love to celebrate together.',
        facts:[
          { text:'Many holidays bring families and friends together.', q:'Who do holidays often bring together?', a:'Families and friends', distractors:['Only strangers','Just one person','Wild animals'] },
          { text:'People often share special foods on a holiday.', q:'What do people often share on holidays?', a:'Special foods', distractors:['Old socks','Homework','Empty boxes'] },
          { text:'Music and dancing are part of many celebrations.' },
          { text:'Some holidays use bright lights or colorful decorations.', q:'What do some holidays use to decorate?', a:'Bright lights or colorful decorations', distractors:['Plain gray paint','Nothing at all','Piles of rocks'] },
          { text:'Different countries have their own special holidays.' },
          { text:'Many holidays help people remember important stories or people.' },
        ],
        inference:{ q:'Why do you think holidays often include sharing food?', a:'Sharing food helps people feel close and joyful together', distractors:['Food makes holidays shorter','People do not like to talk','It saves money'] },
        vocab:{ word:'celebrate', meaning:'to do something special for a happy event', distractors:['to clean the house','to take a test','to fall asleep'] } },
      { label:'Lunar New Year',
        titles:['Lunar New Year','A Bright Celebration','Welcoming the New Year'],
        intro:'Lunar New Year is a holiday celebrated by many people in Asia and around the world.',
        theme:'Lunar New Year welcomes a fresh new year with family, food, and color.',
        closer:'Lunar New Year is a joyful time of hope for the year ahead.',
        facts:[
          { text:'The color red is very common during Lunar New Year because it stands for good luck.', q:'What does the color red stand for at Lunar New Year?', a:'Good luck', distractors:['Sadness','Cold weather','Bedtime'] },
          { text:'Families gather to share a big special meal together.', q:'What do families do at Lunar New Year?', a:'Share a big special meal', distractors:['Go to school','Clean the streets','Stay apart'] },
          { text:'Children often receive red envelopes with money inside.', q:'What do children often receive?', a:'Red envelopes with money', distractors:['New shoes','Big rocks','Homework'] },
          { text:'Colorful dragon and lion dances fill the streets.' },
          { text:'Each year is named after an animal, like the rabbit or the dragon.' },
          { text:'People wish each other happiness and good fortune.' },
        ],
        inference:{ q:'Why might red envelopes make children feel happy?', a:'They are a gift that brings good wishes and a little money', distractors:['They are very heavy','They are full of homework','They taste good'] },
        vocab:{ word:'fortune', meaning:'good luck', distractors:['a kind of food','a loud drum','a tall building'] } },
    ],
  },
  food: {
    subjects:[
      { label:'Where Bread Comes From',
        titles:['Where Bread Comes From','From Wheat to Bread','How Bread Is Made'],
        intro:'Bread is a food that starts as a plant in a field.',
        theme:'Bread travels a long way, from a wheat field to your table.',
        closer:'The next time you eat bread, remember the long journey it took.',
        facts:[
          { text:'Bread begins as a plant called wheat that grows in fields.', q:'What plant does bread come from?', a:'Wheat', distractors:['Corn','Rice','Beans'] },
          { text:'Wheat is ground into a soft powder called flour.', q:'What is wheat ground into?', a:'Flour', distractors:['Sugar','Salt','Sand'] },
          { text:'Flour is mixed with water and other things to make dough.', q:'What do you make when you mix flour and water?', a:'Dough', distractors:['Soup','Juice','Paint'] },
          { text:'The dough is baked in a hot oven until it becomes bread.' },
          { text:'Yeast is a tiny helper that makes the dough puff up and rise.' },
          { text:'Bakers shape dough into loaves, rolls, and many other kinds of bread.' },
        ],
        inference:{ q:'Why does bread need a baker and an oven?', a:'Dough has to be baked with heat to turn into bread', distractors:['Bread grows ready on the plant','Ovens keep bread cold','Bakers eat all the wheat'] },
        vocab:{ word:'dough', meaning:'a soft mix of flour and water before baking', distractors:['a finished loaf','a glass of milk','a baking pan'] } },
      { label:'Healthy Fruits',
        titles:['Healthy Fruits','Good-for-You Fruits','Fruit Power'],
        intro:'Fruits are sweet, healthy foods that grow on plants and trees.',
        theme:'Fruits give our bodies vitamins that help us stay healthy.',
        closer:'Eating a rainbow of fruits helps keep your body strong.',
        facts:[
          { text:'Fruits are full of vitamins that help your body stay strong.', q:'Why are fruits good for you?', a:'They are full of vitamins', distractors:['They are full of sand','They have no taste','They are made of plastic'] },
          { text:'Many fruits, like apples and oranges, grow on trees.', q:'Where do apples and oranges grow?', a:'On trees', distractors:['Underground','In the ocean','On rocks'] },
          { text:'Berries are small fruits that grow on low bushes.' },
          { text:'Eating different colors of fruit gives your body different vitamins.', q:'Why eat fruits of different colors?', a:'Different colors give different vitamins', distractors:['Colors taste the same','It looks messy','Color does not matter'] },
          { text:'Fruits have natural sugar that gives you energy.' },
          { text:'Washing fruit before you eat it helps keep you healthy.' },
        ],
        inference:{ q:'Why is it a good idea to eat many kinds of fruit?', a:'Different fruits give your body different vitamins', distractors:['One fruit is enough forever','Fruit is bad for you','Fruit makes you sleepy'] },
        vocab:{ word:'vitamins', meaning:'tiny things in food that keep you healthy', distractors:['kinds of candy','small seeds','drops of water'] } },
    ],
  },
  transportation: {
    subjects:[
      { label:'Trains',
        titles:['All About Trains','Train Facts','Riding the Rails'],
        intro:'A train is a long line of cars that rides on metal tracks.',
        theme:'Trains carry people and heavy goods along metal tracks.',
        closer:'Trains can carry huge loads a long way, faster than a truck.',
        facts:[
          { text:'Trains run on two metal rails called a track.', q:'What do trains run on?', a:'Metal rails called a track', distractors:['A wide road','Ocean waves','A long rope'] },
          { text:'The engine at the front pulls all the other cars.', q:'What part of the train pulls the cars?', a:'The engine', distractors:['The last car','The wheels alone','The windows'] },
          { text:'Some trains carry people, and others carry heavy goods like coal or cars.', q:'What can trains carry?', a:'People and heavy goods', distractors:['Only water','Only mail','Nothing at all'] },
          { text:'A long freight train can have a hundred cars or more.' },
          { text:'Trains can travel a long way without stopping.' },
          { text:'Train tracks cross roads at places with gates and flashing lights.' },
        ],
        inference:{ q:'Why might a train be useful for moving very heavy loads?', a:'It can pull many cars full of goods at once', distractors:['It can fly over hills','It floats on water','It folds up small'] },
        vocab:{ word:'engine', meaning:'the part that powers and pulls the train', distractors:['the back window','a train ticket','the station floor'] } },
      { label:'Airplanes',
        titles:['All About Airplanes','Airplane Facts','Flying High'],
        intro:'An airplane is a machine that carries people and things through the air.',
        theme:'Airplanes use wings and engines to fly high above the ground.',
        closer:'Airplanes let people travel far across the world in just hours.',
        facts:[
          { text:'Airplanes have wings that help lift them into the air.', q:'What helps an airplane lift into the air?', a:'Its wings', distractors:['Its wheels','Its windows','Its seats'] },
          { text:'Powerful engines push the plane fast enough to fly.', q:'What pushes a plane fast enough to fly?', a:'Powerful engines', distractors:['Strong wind only','Flapping wings','A long rope'] },
          { text:'A pilot sits in the front and flies the airplane.', q:'Who flies the airplane?', a:'A pilot', distractors:['A passenger','A robot dog','No one'] },
          { text:'Airplanes take off and land at a place called an airport.' },
          { text:'Planes fly so high that the clouds are below them.' },
          { text:'Airplanes can carry people across the whole world.' },
        ],
        inference:{ q:'Why might people choose a plane for a very long trip?', a:'A plane can travel very far very quickly', distractors:['Planes are the slowest way','Planes cannot go far','Planes only go in circles'] },
        vocab:{ word:'pilot', meaning:'the person who flies the plane', distractors:['a kind of wing','an airport','a flight ticket'] } },
    ],
  },
  seasons: {
    subjects:[
      { label:'Why We Have Seasons',
        titles:['Why We Have Seasons','The Four Seasons','Earth and the Sun'],
        intro:'A year has four seasons: spring, summer, autumn, and winter.',
        theme:'The four seasons happen as Earth travels around the Sun.',
        closer:'Each season brings its own weather, and together they make a whole year.',
        facts:[
          { text:'The four seasons are spring, summer, autumn, and winter.', q:'How many seasons are in a year?', a:'Four', distractors:['Two','Seven','Twelve'] },
          { text:'In summer the days are warm and long.', q:'What are summer days like?', a:'Warm and long', distractors:['Cold and short','Dark all day','Always rainy'] },
          { text:'In winter the days are cold and short.' },
          { text:'In spring, plants begin to grow and flowers bloom.', q:'What happens to plants in spring?', a:'They begin to grow and bloom', distractors:['They all die','They turn to stone','They fly away'] },
          { text:'In autumn, leaves change color and fall from the trees.' },
          { text:'The seasons change because Earth travels around the Sun all year.' },
        ],
        inference:{ q:'Why might you wear a heavy coat in one season but not another?', a:'Because each season has different weather', distractors:['Coats only fit in summer','The Sun disappears','Clothes change color'] },
        vocab:{ word:'bloom', meaning:'to open into a flower', distractors:['to fall asleep','to turn brown','to freeze solid'] } },
      { label:'Autumn',
        titles:['All About Autumn','Autumn Facts','The Fall Season'],
        intro:'Autumn, also called fall, comes after summer and before winter.',
        theme:'Autumn is a season of cooler air and colorful falling leaves.',
        closer:'Autumn is a beautiful, crunchy season as the world gets ready for winter.',
        facts:[
          { text:'In autumn, the leaves turn red, orange, yellow, and brown.', q:'What colors do leaves turn in autumn?', a:'Red, orange, yellow, and brown', distractors:['Blue and purple','Black and white','They stay green'] },
          { text:'The air gets cooler as autumn goes on.', q:'How does the air change in autumn?', a:'It gets cooler', distractors:['It gets hotter','It disappears','It turns wet only'] },
          { text:'Many trees drop all their leaves before winter.' },
          { text:'Farmers harvest crops like pumpkins and apples in autumn.', q:'What do farmers harvest in autumn?', a:'Crops like pumpkins and apples', distractors:['Ice cream','Toys','Snowballs'] },
          { text:'The days slowly get shorter during autumn.' },
          { text:'Some animals gather food in autumn to get ready for winter.' },
        ],
        inference:{ q:'Why might squirrels gather nuts in autumn?', a:'To store food for the cold winter ahead', distractors:['To throw them at trees','Because nuts are too heavy','To plant a garden'] },
        vocab:{ word:'harvest', meaning:'to gather crops that are ready', distractors:['to plant a seed','to water a field','to chop down a tree'] } },
    ],
  },
  plants: {
    subjects:[
      { label:'How Seeds Grow',
        titles:['How Seeds Grow','From Seed to Plant','The Life of a Seed'],
        intro:'Almost every plant begins its life as a tiny seed.',
        theme:'A seed grows into a plant when it has soil, water, and sunlight.',
        closer:'With the right care, a tiny seed can grow into a tall, strong plant.',
        facts:[
          { text:'A seed needs water, sunlight, and soil to grow.', q:'What does a seed need to grow?', a:'Water, sunlight, and soil', distractors:['Only darkness','Sand and salt','Nothing at all'] },
          { text:'First, a tiny root grows down into the soil.', q:'What grows down into the soil first?', a:'A tiny root', distractors:['A bright flower','A green leaf','A piece of fruit'] },
          { text:'Then a small green shoot pushes up toward the light.', q:'Which way does the green shoot grow?', a:'Up toward the light', distractors:['Down into the rock','Sideways forever','Into the water'] },
          { text:'Roots drink water from the soil to feed the plant.' },
          { text:'Leaves use sunlight to help the plant make its own food.' },
          { text:'With time and care, the plant grows tall and may make new seeds.' },
        ],
        inference:{ q:'Why might a seed in a dark closet not grow well?', a:'It would not get the sunlight it needs', distractors:['Closets are too windy','Seeds like to be alone','It would grow too fast'] },
        vocab:{ word:'shoot', meaning:'the new green part of a young plant', distractors:['a kind of seed','a deep hole','a falling leaf'] } },
      { label:'Trees',
        titles:['All About Trees','Tree Facts','Giants of the Forest'],
        intro:'Trees are tall plants that can live for many, many years.',
        theme:'Trees give us shade, clean air, and homes for animals.',
        closer:'Trees are some of the most helpful living things on Earth.',
        facts:[
          { text:'Trees make a gas called oxygen that people and animals need to breathe.', q:'What helpful gas do trees make?', a:'Oxygen, which we breathe', distractors:['Smoke','Rain','Sand'] },
          { text:'Roots hold a tree in place and drink water from the soil.', q:'What do a tree\'s roots do?', a:'Hold it in place and drink water', distractors:['Make the leaves fall','Help it walk','Keep it warm'] },
          { text:'Many animals, like birds and squirrels, make their homes in trees.', q:'Who makes their home in trees?', a:'Animals like birds and squirrels', distractors:['Fish and whales','Cars and trucks','No one'] },
          { text:'A tree\'s leaves catch sunlight to help it make food.' },
          { text:'Some trees grow taller than a house.' },
          { text:'You can guess a tree\'s age by counting the rings inside its trunk.' },
        ],
        inference:{ q:'Why are trees important for the air we breathe?', a:'They make oxygen that people and animals need', distractors:['They make the wind blow','They block out the Sun','They use up all the air'] },
        vocab:{ word:'oxygen', meaning:'the gas in air that we breathe', distractors:['a kind of leaf','a tree root','a drop of sap'] } },
    ],
  },
  mysteries: {
    subjects:[
      { label:'How Detectives Work',
        titles:['How Detectives Work','Solving Mysteries','Following the Clues'],
        intro:'A detective is a person who solves mysteries by finding clues.',
        theme:'Detectives gather clues and think carefully to solve a mystery.',
        closer:'Anyone who looks closely and thinks hard can solve a mystery.',
        facts:[
          { text:'A clue is a hint that helps a detective figure out what happened.', q:'What is a clue?', a:'A hint that helps solve a mystery', distractors:['A kind of hat','A loud noise','A heavy box'] },
          { text:'Detectives look very closely at things others might miss.', q:'How do detectives find clues?', a:'By looking very closely', distractors:['By closing their eyes','By guessing fast','By asking no one'] },
          { text:'Detectives ask questions to learn what people saw or heard.', q:'Why do detectives ask questions?', a:'To learn what people saw or heard', distractors:['To pass the time','To win a prize','To make noise'] },
          { text:'Good detectives stay calm and patient while they search.' },
          { text:'They put the clues together like pieces of a puzzle.' },
          { text:'Once the clues fit, the detective can solve the mystery.' },
        ],
        inference:{ q:'Why is it helpful for a detective to be patient?', a:'Finding and fitting clues together takes careful time', distractors:['Patience makes clues appear','Mysteries solve themselves','Being slow is always best'] },
        vocab:{ word:'clue', meaning:'a hint that helps you figure something out', distractors:['a magnifying glass','a long coat','a locked door'] } },
      { label:'Fingerprints',
        titles:['All About Fingerprints','Fingerprint Facts','Your Secret Pattern'],
        intro:'Fingerprints are the tiny patterns of lines on your fingertips.',
        theme:'Everyone has fingerprints, and no two people share the same ones.',
        closer:'Your fingerprints are a pattern that belongs only to you.',
        facts:[
          { text:'No two people have exactly the same fingerprints.', q:'What is special about fingerprints?', a:'No two people have the same ones', distractors:['Everyone shares one set','They change every day','Only adults have them'] },
          { text:'Even twins have different fingerprints.', q:'Do twins have the same fingerprints?', a:'No, even twins have different ones', distractors:['Yes, exactly the same','Twins have no prints','Only one twin has them'] },
          { text:'Fingerprints leave a mark when you touch something.', q:'When do fingerprints leave a mark?', a:'When you touch something', distractors:['Only when you sleep','Only in water','Only at night'] },
          { text:'Detectives can use fingerprints to learn who touched an object.' },
          { text:'Your fingerprints stay the same your whole life.' },
          { text:'The lines on a fingertip make loops, whorls, and arches.' },
        ],
        inference:{ q:'Why are fingerprints useful for solving a mystery?', a:'They can show exactly who touched something', distractors:['They glow in the dark','They tell the time','They can talk'] },
        vocab:{ word:'pattern', meaning:'a design that repeats', distractors:['a loud sound','a sticky glue','a bright light'] } },
    ],
  },
  'school adventures': {
    subjects:[
      { label:'A Day at School',
        titles:['A Day at School','School Time','Learning Each Day'],
        intro:'At school, children learn new things and play with friends.',
        theme:'A school day is full of learning, friends, and fun activities.',
        closer:'Every school day brings a new chance to learn and grow.',
        facts:[
          { text:'A teacher helps the class learn reading, writing, and math.', q:'Who helps the class learn?', a:'A teacher', distractors:['The principal\'s dog','A robot','No one'] },
          { text:'At recess, children get to play outside and move around.', q:'What do children do at recess?', a:'Play outside and move around', distractors:['Take a test','Go to sleep','Stay very still'] },
          { text:'Students often work together in small groups.', q:'How do students often work?', a:'Together in small groups', distractors:['Always alone','Only at home','In total silence'] },
          { text:'The school day follows a schedule, with a time for each subject.' },
          { text:'Lunchtime gives everyone a chance to eat and rest.' },
          { text:'Each day, students learn something new to add to what they know.' },
        ],
        inference:{ q:'Why might a schedule help a school day go smoothly?', a:'Everyone knows what to do and when to do it', distractors:['It makes the day longer','It hides the clock','It cancels recess'] },
        vocab:{ word:'schedule', meaning:'a plan that shows when things happen', distractors:['a kind of pencil','a school bus','a lunch tray'] } },
      { label:'The School Library',
        titles:['The School Library','All About the Library','A World of Books'],
        intro:'The library is a quiet place at school that is full of books.',
        theme:'The library is a place to find books and learn new things.',
        closer:'The library is a treasure chest of stories waiting to be read.',
        facts:[
          { text:'A library holds books on almost any subject you can think of.', q:'What does a library hold?', a:'Books on almost any subject', distractors:['Only toys','Only food','Only games'] },
          { text:'A librarian helps you find the book you are looking for.', q:'Who helps you find a book?', a:'A librarian', distractors:['A lifeguard','A pilot','A chef'] },
          { text:'You can borrow a book and take it home for a while.', q:'What does it mean to borrow a book?', a:'To take it home for a while and return it', distractors:['To keep it forever','To color in it','To throw it away'] },
          { text:'Books in a library are sorted so they are easy to find.' },
          { text:'Libraries are quiet so everyone can read and think.' },
          { text:'When you finish a borrowed book, you return it for someone else to enjoy.' },
        ],
        inference:{ q:'Why are library books sorted into an order?', a:'So people can find the book they want quickly', distractors:['To make them heavier','So no one can read them','To keep them warm'] },
        vocab:{ word:'borrow', meaning:'to take something for a while and give it back', distractors:['to keep forever','to buy a new one','to tear it up'] } },
    ],
  },
};

// flatten subject labels for distractors
const SUBJECT_LABELS = [];
Object.values(NONFICTION_PACKS).forEach(p=> p.subjects.forEach(s=> SUBJECT_LABELS.push(s.label)));

Object.assign(window, { NONFICTION_PACKS, SUBJECT_LABELS });
