// ====== OFFLINE FICTION CONTENT PACKS (all topics) ======
// Each episode is self-contained so a randomly assembled story stays coherent
// and the questions derived from it are always correct.
// Slot grammar:
//   want:     completes "[NAME] ____."        e.g. "wanted to find the lost kite"
//   trigger:  completes "One day, [NAME] ____." (past-tense verb phrase)
//   problem:  completes "But ____."            (clause)
//   help:     completes "Then ____."           (clause)
//   solution: completes "[NAME] ____, and felt very <feeling>."
//   lesson:   completes "From that day on, [NAME] knew that ____."
//   mainIdea: completes "A <kind> who ____."   (3rd-person verb phrase)

const FICTION_PACKS = {
  animals: {
    heroes:[{name:'Finn',kind:'fox'},{name:'Pip',kind:'rabbit'},{name:'Rosa',kind:'deer'},{name:'Milo',kind:'badger'}],
    settings:[{prose:'near a big green hill',label:'By a green hill'},{prose:'deep in a cozy forest',label:'In the forest'},{prose:'beside a bubbling creek',label:'By a creek'}],
    episodes:[
      { feeling:'proud',
        want:'wanted to find the sweetest berries in the whole woods',
        trigger:'spotted a bush full of ripe berries at the top of a steep slope',
        problem:'the slope was rocky and a little scary to climb',
        help:'a friendly bird showed a gentle path that wound around the rocks',
        solution:'followed the easy path and filled a basket to the brim',
        lesson:'asking for help can make a hard job feel easy',
        mainIdea:'works with a friend to reach a tricky goal',
        detail:'The berries were [NAME]\'s very favorite snack.',
        extra:'[NAME] shared the berries with everyone back home.',
        vocab:{word:'gentle',sentence:'The gentle path was smooth and easy, not steep at all.',meaning:'soft and easy, not rough',distractors:['very loud and fast','tall and pointy','cold and wet']},
        titles:['The Berry Hunt','[NAME]\'s Big Climb','Berries on the Hill'],
        why:{q:'Why was [NAME] able to fill the basket?',a:'Because a friend showed an easier path',distractors:['Because the hill was made of candy','Because it started to rain','Because the basket was magic']} },
      { feeling:'happy',
        want:'wanted to build the warmest nest before the cold night came',
        trigger:'gathered soft moss and leaves from all around the meadow',
        problem:'a gust of wind blew the pile away across the grass',
        help:'two little friends came running to help catch every leaf',
        solution:'tucked the nest into a safe hollow and made it snug',
        lesson:'good friends turn a big job into a fun one',
        mainIdea:'builds a cozy home with the help of friends',
        detail:'The night was going to be very chilly.',
        extra:'Everyone curled up together, warm and safe.',
        vocab:{word:'snug',sentence:'Inside the hollow it was snug, warm, and out of the wind.',meaning:'warm and cozy',distractors:['wet and muddy','big and empty','bright and noisy']},
        titles:['The Cozy Nest','A Warm Night','[NAME] Builds a Home'],
        why:{q:'Why did [NAME] need help?',a:'Because the wind kept blowing the nest away',distractors:['Because it was a sunny day','Because the nest was too heavy','Because [NAME] was sleepy']} },
    ],
  },
  space: {
    heroes:[{name:'Luna',kind:'astronaut'},{name:'Zip',kind:'little robot'},{name:'Cosmo',kind:'star sprite'},{name:'Ravi',kind:'space cadet'}],
    settings:[{prose:'on a shiny silver space station',label:'On a space station'},{prose:'aboard a tiny rocket ship',label:'In a rocket'},{prose:'on a quiet moon base',label:'On the moon'}],
    episodes:[
      { feeling:'excited',
        want:'wanted to see the rings of a faraway planet up close',
        trigger:'pointed the little rocket toward the glowing planet',
        problem:'a cloud of space dust hid the rings from view',
        help:'a wise old satellite beeped out the safest way around',
        solution:'steered gently past the dust and saw the rings sparkle',
        lesson:'patience helps you reach a faraway goal',
        mainIdea:'travels through space to discover something amazing',
        detail:'The rings shone like a giant golden hoop.',
        extra:'[NAME] drew a picture to remember the trip.',
        vocab:{word:'faraway',sentence:'The faraway planet was so distant it looked like a tiny dot.',meaning:'very far in distance',distractors:['close and near','small and round','warm and soft']},
        titles:['The Shining Rings','[NAME] in Space','A Trip to the Planet'],
        why:{q:'Why couldn\'t [NAME] see the rings at first?',a:'Because a cloud of space dust was in the way',distractors:['Because the rocket was upside down','Because it was nighttime','Because [NAME] closed both eyes']} },
      { feeling:'proud',
        want:'wanted to fix the blinking light on the space station',
        trigger:'floated down a long hallway toward the blinking control panel',
        problem:'the toolbox drifted away and bumped against the ceiling',
        help:'a kind crewmate grabbed the floating tools just in time',
        solution:'tightened the loose wire and made the light glow steady',
        lesson:'teamwork keeps everyone safe up in space',
        mainIdea:'fixes a problem on the station with a teammate',
        detail:'In space, things float if you let them go.',
        extra:'The whole crew cheered when the light came on.',
        vocab:{word:'drifted',sentence:'The toolbox drifted slowly away, floating in the air.',meaning:'floated slowly along',distractors:['fell down fast','stayed still','grew much bigger']},
        titles:['The Blinking Light','Fix-It in Space','[NAME] Saves the Day'],
        why:{q:'Why did the tools float away?',a:'Because things float in space',distractors:['Because the door was open','Because [NAME] threw them','Because they were too heavy']} },
    ],
  },
  ocean: {
    heroes:[{name:'Coral',kind:'sea turtle'},{name:'Bubbles',kind:'dolphin'},{name:'Finn',kind:'little fish'},{name:'Pearl',kind:'octopus'}],
    settings:[{prose:'in a colorful coral reef',label:'In a coral reef'},{prose:'near a sunken pirate ship',label:'By a sunken ship'},{prose:'in a quiet seagrass bay',label:'In a seagrass bay'}],
    episodes:[
      { feeling:'joyful',
        want:'wanted to find the lost pearl that fell from a giant clam',
        trigger:'searched between the swaying seagrass for a glint of white',
        problem:'the water grew dark and it was hard to see',
        help:'a glowing jellyfish lit the way with a soft blue shine',
        solution:'found the pearl tucked under a rock and carried it home',
        lesson:'a little light from a friend goes a long way',
        mainIdea:'searches the sea and finds a lost treasure',
        detail:'The pearl was as round as a marble.',
        extra:'The giant clam smiled a slow, happy smile.',
        vocab:{word:'glint',sentence:'A tiny glint of white sparkled between the green seagrass.',meaning:'a small flash of light',distractors:['a loud splash','a dark hole','a heavy rock']},
        titles:['The Lost Pearl','[NAME] and the Glow','Treasure in the Reef'],
        why:{q:'Why was it hard for [NAME] to see?',a:'Because the water grew dark',distractors:['Because [NAME] was sleeping','Because the sun was too bright','Because the pearl was loud']} },
      { feeling:'grateful',
        want:'wanted to free a friend tangled in an old fishing net',
        trigger:'swam fast toward a soft, worried cry near the reef',
        problem:'the net was knotted tight and would not come loose',
        help:'a clever crab snipped the ropes with two strong claws',
        solution:'pulled the net away and set the friend free at last',
        lesson:'helping others is the kindest thing you can do',
        mainIdea:'rescues a friend who is in trouble',
        detail:'The net had drifted in from far away.',
        extra:'The two friends did a happy loop together.',
        vocab:{word:'tangled',sentence:'The net was tangled, with ropes twisted all around.',meaning:'twisted up in knots',distractors:['shiny and new','flat and smooth','small and dry']},
        titles:['The Tangled Net','[NAME] to the Rescue','Free Again'],
        why:{q:'How was the friend set free?',a:'A crab snipped the ropes with its claws',distractors:['The net melted in the sun','A wave washed it away','[NAME] sang a song']} },
    ],
  },
  weather: {
    heroes:[{name:'Sky',kind:'cloud sprite'},{name:'Dewey',kind:'raindrop'},{name:'Sunny',kind:'sunbeam'},{name:'Gale',kind:'wind whisp'}],
    settings:[{prose:'high up in the fluffy clouds',label:'In the clouds'},{prose:'over a green farm valley',label:'Over a valley'},{prose:'above a sleepy little town',label:'Above a town'}],
    episodes:[
      { feeling:'happy',
        want:'wanted to water the thirsty flowers in the valley below',
        trigger:'gathered a big puffy cloud full of cool raindrops',
        problem:'a strong wind pushed the cloud the wrong way',
        help:'a gentle breeze nudged the cloud back over the flowers',
        solution:'let the rain fall softly until every flower had a drink',
        lesson:'even the weather works best when friends team up',
        mainIdea:'brings rain to help the thirsty flowers grow',
        detail:'The flowers had been droopy and dry all week.',
        extra:'A bright rainbow stretched across the sky after.',
        vocab:{word:'thirsty',sentence:'The thirsty flowers had no water and looked very droopy.',meaning:'needing water badly',distractors:['full of water','tall and strong','red and shiny']},
        titles:['The Rain Helper','[NAME] and the Flowers','A Drink for the Valley'],
        why:{q:'Why did the flowers need [NAME]?',a:'Because they were thirsty and dry',distractors:['Because they were too wet','Because they were lost','Because they wanted shade']} },
      { feeling:'proud',
        want:'wanted to clear the fog so the town could see the morning sun',
        trigger:'floated low over the streets where thick fog had settled',
        problem:'the fog was so heavy that no one could find their way',
        help:'a warm sunbeam joined in to lift the mist away',
        solution:'swept the fog up high until the whole town sparkled',
        lesson:'a little warmth can clear away a gloomy day',
        mainIdea:'clears the fog so the town can see again',
        detail:'The fog had hidden every roof and tree.',
        extra:'The townsfolk waved up at the bright clear sky.',
        vocab:{word:'mist',sentence:'The mist was a thin, damp cloud floating near the ground.',meaning:'a thin, damp cloud near the ground',distractors:['a pile of dry leaves','a loud thunder boom','a warm sunny beam']},
        titles:['Clearing the Fog','[NAME] and the Sun','A Bright Morning'],
        why:{q:'How was the fog cleared away?',a:'A warm sunbeam helped lift the mist',distractors:['A truck blew it away','It turned into snow','[NAME] ate it up']} },
    ],
  },
  friendship: {
    heroes:[{name:'Mia',kind:'girl'},{name:'Theo',kind:'boy'},{name:'Ruby',kind:'kid'},{name:'Sam',kind:'child'}],
    settings:[{prose:'in a sunny school yard',label:'At the school yard'},{prose:'on a friendly neighborhood street',label:'On their street'},{prose:'at a bright community park',label:'At the park'}],
    episodes:[
      { feeling:'happy',
        want:'wanted to cheer up a new friend who felt left out',
        trigger:'noticed a new kid sitting all alone at the edge of the yard',
        problem:'the new kid was too shy to come and play',
        help:'a couple of classmates brought over a ball and a big smile',
        solution:'invited the new friend into the game and played together',
        lesson:'a kind invitation can turn a stranger into a friend',
        mainIdea:'helps a lonely classmate feel welcome',
        detail:'It is no fun to feel left out.',
        extra:'By lunchtime they were all laughing together.',
        vocab:{word:'shy',sentence:'The new kid felt shy and was too nervous to say hello.',meaning:'quiet and nervous around others',distractors:['loud and bossy','sleepy and slow','fast and strong']},
        titles:['A New Friend','[NAME] Says Hello','Come Play!'],
        why:{q:'Why did the new kid sit alone at first?',a:'Because the new kid was too shy to join',distractors:['Because the yard was closed','Because it was raining','Because the kid was angry']} },
      { feeling:'grateful',
        want:'wanted to make up after a silly argument with a best friend',
        trigger:'remembered the fun the two friends always had together',
        problem:'both friends felt too stubborn to say sorry first',
        help:'a kind teacher reminded them how much they cared',
        solution:'said sorry at the same time and shared a big laugh',
        lesson:'saying sorry is brave, and it mends a friendship',
        mainIdea:'makes up with a friend after a fight',
        detail:'The argument had started over something very small.',
        extra:'They promised to talk it out next time.',
        vocab:{word:'stubborn',sentence:'They were both stubborn and would not give in or say sorry.',meaning:'not willing to change your mind',distractors:['happy and silly','quick and clever','kind and gentle']},
        titles:['Friends Again','The Big Sorry','[NAME] Makes Up'],
        why:{q:'Why didn\'t the friends make up right away?',a:'Because both were too stubborn to say sorry',distractors:['Because they moved away','Because school was over','Because they forgot each other']} },
    ],
  },
  sports: {
    heroes:[{name:'Jay',kind:'young player'},{name:'Lola',kind:'sprinter'},{name:'Marco',kind:'goalie'},{name:'Nia',kind:'gymnast'}],
    settings:[{prose:'on a grassy soccer field',label:'On the field'},{prose:'at a busy running track',label:'At the track'},{prose:'inside a bright gym',label:'In the gym'}],
    episodes:[
      { feeling:'proud',
        want:'wanted to score a goal in the big game on Saturday',
        trigger:'practiced kicking the ball again and again after school',
        problem:'every shot kept missing wide of the net',
        help:'a patient coach showed how to aim with the side of the foot',
        solution:'kicked it just right and the ball curved into the goal',
        lesson:'practice and good coaching make hard things possible',
        mainIdea:'practices hard to reach a sports goal',
        detail:'The big game was only a few days away.',
        extra:'The whole team jumped up and cheered.',
        vocab:{word:'aim',sentence:'The coach showed [NAME] how to aim, or point the kick, at the net.',meaning:'to point at a target',distractors:['to run away fast','to fall down','to take a nap']},
        titles:['The Big Goal','[NAME] Scores','Practice Pays Off'],
        why:{q:'Why did [NAME]\'s shots miss at first?',a:'Because [NAME] was not aiming the right way',distractors:['Because the ball was flat','Because it was too sunny','Because the net was gone']} },
      { feeling:'joyful',
        want:'wanted to finish the long race without giving up',
        trigger:'lined up at the start with butterflies in the tummy',
        problem:'halfway through, [NAME]\'s legs felt heavy and tired',
        help:'a teammate ran alongside and cheered every step',
        solution:'kept going all the way to the finish line, slow but steady',
        lesson:'finishing is a win, even if you are not the fastest',
        mainIdea:'keeps going in a race instead of giving up',
        detail:'The track went all the way around the field.',
        extra:'[NAME] got a shiny ribbon just for finishing.',
        vocab:{word:'steady',sentence:'[NAME] ran at a steady pace, the same speed the whole way.',meaning:'staying the same and even',distractors:['stopping and starting','very fast then slow','jumpy and wild']},
        titles:['The Long Race','Never Give Up','[NAME] Finishes Strong'],
        why:{q:'How did [NAME] finish the race?',a:'A teammate cheered and ran alongside',distractors:['A car gave a ride','The race was canceled','[NAME] flew over it']} },
    ],
  },
  dinosaurs: {
    heroes:[{name:'Trudy',kind:'triceratops'},{name:'Rex',kind:'little raptor'},{name:'Spike',kind:'stegosaurus'},{name:'Dot',kind:'baby dino'}],
    settings:[{prose:'in a steamy green jungle',label:'In the jungle'},{prose:'near a wide muddy river',label:'By the river'},{prose:'at the foot of a smoky volcano',label:'By the volcano'}],
    episodes:[
      { feeling:'brave',
        want:'wanted to find the tastiest leaves on the tallest tree',
        trigger:'stretched a long neck up toward the leafy branches',
        problem:'the branches were far too high to reach',
        help:'a tall friend offered a strong back to stand on',
        solution:'climbed up just enough to nibble the juicy leaves',
        lesson:'a good friend can help you reach new heights',
        mainIdea:'works with a friend to reach high leaves',
        detail:'The leaves at the top were the greenest of all.',
        extra:'They shared the leaves and munched happily.',
        vocab:{word:'stretched',sentence:'[NAME] stretched, making the neck as long as it could go.',meaning:'reached out as far as possible',distractors:['curled up tight','sat down to rest','rolled in the mud']},
        titles:['The Tall Tree','[NAME] Reaches High','Leafy Lunch'],
        why:{q:'Why couldn\'t [NAME] reach the leaves alone?',a:'Because the branches were too high',distractors:['Because the tree was tiny','Because [NAME] was full','Because it was raining']} },
      { feeling:'happy',
        want:'wanted to cross the wide river to reach a berry patch',
        trigger:'looked for a safe place to step across the rushing water',
        problem:'the water was deep and moved very fast',
        help:'a row of friendly dinos made a bridge with their backs',
        solution:'crossed step by step and reached the sweet berries',
        lesson:'big problems shrink when everyone pitches in',
        mainIdea:'crosses a river with help from friends',
        detail:'The berry patch was bright red and ripe.',
        extra:'Everyone shared a berry feast on the far bank.',
        vocab:{word:'rushing',sentence:'The rushing river moved fast, splashing over the rocks.',meaning:'moving very fast',distractors:['frozen and still','warm and calm','dry and empty']},
        titles:['Across the River','The Dino Bridge','[NAME]\'s Big Crossing'],
        why:{q:'How did [NAME] cross the river?',a:'Friends made a bridge with their backs',distractors:['[NAME] swam very fast','A boat appeared','The river dried up']} },
    ],
  },
  'community helpers': {
    heroes:[{name:'Officer Dana',kind:'helper'},{name:'Nurse Ben',kind:'helper'},{name:'Captain Joy',kind:'firefighter'},{name:'Mr. Lee',kind:'mail carrier'}],
    settings:[{prose:'in a busy little town',label:'In town'},{prose:'on a friendly main street',label:'On Main Street'},{prose:'near the town fire station',label:'By the fire station'}],
    episodes:[
      { feeling:'proud',
        want:'wanted to help a lost puppy find its way back home',
        trigger:'spotted a tiny puppy shivering by the side of the road',
        problem:'no one knew which house the puppy belonged to',
        help:'a kind neighbor recognized the puppy\'s red collar',
        solution:'walked the puppy safely back to its happy family',
        lesson:'helpers keep the whole town safe and kind',
        mainIdea:'helps a lost puppy get back home',
        detail:'The puppy had a shiny red collar.',
        extra:'The family gave the puppy a big, gentle hug.',
        vocab:{word:'recognized',sentence:'A neighbor recognized the collar, knowing it from before.',meaning:'knew it from before',distractors:['lost it again','never saw it','painted it blue']},
        titles:['The Lost Puppy','[NAME] Helps Out','Home at Last'],
        why:{q:'How was the puppy\'s home found?',a:'A neighbor recognized its red collar',distractors:['The puppy spoke','It started to snow','The puppy was magic']} },
      { feeling:'grateful',
        want:'wanted to make sure everyone got to the library safely',
        trigger:'noticed cars zooming past the busy street corner',
        problem:'the little ones were afraid to cross on their own',
        help:'a crossing guard raised a bright stop sign with a smile',
        solution:'walked every child across the street, safe and sound',
        lesson:'when helpers do their job, everyone can feel safe',
        mainIdea:'helps people cross a busy street safely',
        detail:'The library had a brand-new story time.',
        extra:'Every child waved thank you on the way past.',
        vocab:{word:'zooming',sentence:'The cars were zooming, moving very fast down the street.',meaning:'moving very fast',distractors:['parked and still','rolling slowly','flying in the air']},
        titles:['Crossing Safely','[NAME] at the Corner','To the Library'],
        why:{q:'Why were the little ones afraid?',a:'Because cars were zooming past the corner',distractors:['Because it was dark out','Because the library was closed','Because they were hungry']} },
    ],
  },
  camping: {
    heroes:[{name:'Tess',kind:'camper'},{name:'Owen',kind:'scout'},{name:'Ivy',kind:'hiker'},{name:'Max',kind:'kid'}],
    settings:[{prose:'in a tall pine forest',label:'In the pine woods'},{prose:'beside a calm blue lake',label:'By the lake'},{prose:'on a grassy mountain meadow',label:'On a meadow'}],
    episodes:[
      { feeling:'proud',
        want:'wanted to set up the tent before the sun went down',
        trigger:'spread out the tent poles and bright nylon cover',
        problem:'the poles kept slipping and the tent flopped over',
        help:'an older camper showed how to lock each pole in place',
        solution:'snapped the poles together and the tent stood up tall',
        lesson:'a new skill is easy once someone shows you how',
        mainIdea:'learns to put up a tent with help',
        detail:'The sky was turning pink and orange.',
        extra:'They roasted marshmallows once the tent was up.',
        vocab:{word:'slipping',sentence:'The poles kept slipping, sliding out of [NAME]\'s hands.',meaning:'sliding out of place',distractors:['holding tight','growing taller','turning warm']},
        titles:['Setting Up Camp','[NAME]\'s Tent','Before Dark'],
        why:{q:'Why did the tent keep flopping over?',a:'Because the poles kept slipping out',distractors:['Because the wind blew it','Because it was too heavy','Because a bear sat on it']} },
      { feeling:'excited',
        want:'wanted to follow the trail to a hidden waterfall',
        trigger:'set off down the winding path with a little map',
        problem:'the trail split in two and [NAME] wasn\'t sure which way',
        help:'a park ranger pointed to the marker on the right path',
        solution:'took the marked trail and found the sparkling waterfall',
        lesson:'reading the signs helps you find your way',
        mainIdea:'follows a trail to a hidden waterfall',
        detail:'The waterfall could be heard before it was seen.',
        extra:'[NAME] splashed in the cool misty spray.',
        vocab:{word:'winding',sentence:'The winding path curved this way and that through the trees.',meaning:'full of curves and turns',distractors:['short and straight','steep and tall','wet and slippery']},
        titles:['The Hidden Waterfall','Which Way?','[NAME] Finds the Falls'],
        why:{q:'How did [NAME] choose the right trail?',a:'A ranger pointed to the trail marker',distractors:['[NAME] flipped a coin','The waterfall called out','A map fell from the sky']} },
    ],
  },
  insects: {
    heroes:[{name:'Buzz',kind:'honeybee'},{name:'Lily',kind:'ladybug'},{name:'Gus',kind:'ant'},{name:'Flit',kind:'butterfly'}],
    settings:[{prose:'in a sunny flower garden',label:'In the garden'},{prose:'on a tall blade of grass',label:'On the grass'},{prose:'under a big leafy plant',label:'Under a leaf'}],
    episodes:[
      { feeling:'happy',
        want:'wanted to carry a crumb of bread back to the ant hill',
        trigger:'found a crumb that was much bigger than expected',
        problem:'the crumb was far too heavy to lift alone',
        help:'a line of ant friends marched over to lend their legs',
        solution:'lifted the crumb together and carried it home',
        lesson:'many small helpers can move a big load',
        mainIdea:'works with others to carry something heavy',
        detail:'The crumb was as big as [NAME]\'s whole head.',
        extra:'The whole ant hill shared a tasty meal.',
        vocab:{word:'marched',sentence:'The ants marched, walking in a straight, steady line.',meaning:'walked in a steady line',distractors:['flew away fast','rolled in a ball','fell asleep']},
        titles:['The Heavy Crumb','[NAME] and the Ants','Teamwork!'],
        why:{q:'Why couldn\'t [NAME] carry the crumb alone?',a:'Because it was far too heavy',distractors:['Because it was too small','Because it was sticky','Because it floated away']} },
      { feeling:'joyful',
        want:'wanted to find the brightest flower full of sweet nectar',
        trigger:'flew over the garden looking for a flash of color',
        problem:'a gray cloud rolled in and hid the sun',
        help:'a friendly butterfly knew a patch that always bloomed',
        solution:'sipped the sweet nectar and danced from bloom to bloom',
        lesson:'a friend who knows the way is a wonderful gift',
        mainIdea:'searches the garden for sweet nectar',
        detail:'Nectar is the sweet juice deep inside a flower.',
        extra:'[NAME] hummed a happy buzzing tune.',
        vocab:{word:'nectar',sentence:'The flower was full of nectar, a sweet juice insects love.',meaning:'sweet juice inside a flower',distractors:['a green leaf','a hard seed','a drop of rain']},
        titles:['Sweet Nectar','[NAME] in the Garden','The Brightest Bloom'],
        why:{q:'How did [NAME] find the blooming flowers?',a:'A butterfly knew a patch that always bloomed',distractors:['[NAME] dug underground','The flowers shouted','It was pure luck']} },
    ],
  },
  holidays: {
    heroes:[{name:'Noor',kind:'kid'},{name:'Eli',kind:'child'},{name:'Aria',kind:'girl'},{name:'Diego',kind:'boy'}],
    settings:[{prose:'in a cozy decorated home',label:'At home'},{prose:'at a bright town festival',label:'At the festival'},{prose:'in a sparkly school hall',label:'At school'}],
    episodes:[
      { feeling:'joyful',
        want:'wanted to make a special surprise for the family holiday',
        trigger:'gathered paper, glue, and a jar of glitter at the table',
        problem:'the glitter spilled and made a big sparkly mess',
        help:'a grandparent gently helped sweep and start again',
        solution:'finished a beautiful card that made everyone smile',
        lesson:'a small mess is okay when you keep trying',
        mainIdea:'makes a holiday surprise for the family',
        detail:'The holiday was [NAME]\'s favorite time of year.',
        extra:'The card hung proudly on the wall all season.',
        vocab:{word:'gathered',sentence:'[NAME] gathered the supplies, collecting them in one place.',meaning:'collected together',distractors:['threw away','hid from sight','broke in two']},
        titles:['The Holiday Surprise','[NAME]\'s Card','A Sparkly Mess'],
        why:{q:'Why did [NAME] need to start again?',a:'Because the glitter spilled and made a mess',distractors:['Because the lights went out','Because the card flew away','Because it was bedtime']} },
      { feeling:'grateful',
        want:'wanted everyone to feel included at the big celebration',
        trigger:'noticed a quiet neighbor watching from the doorway',
        problem:'the neighbor wasn\'t sure if they were invited in',
        help:'the whole family waved and pulled up an extra chair',
        solution:'welcomed the neighbor to share the food and fun',
        lesson:'holidays are happiest when everyone is welcome',
        mainIdea:'makes sure a neighbor feels included',
        detail:'The table was full of warm, tasty food.',
        extra:'The neighbor brought a song to share, too.',
        vocab:{word:'included',sentence:'Everyone was included, with a place for each person.',meaning:'made part of the group',distractors:['left outside','sent away','kept secret']},
        titles:['A Warm Welcome','[NAME]\'s Big Heart','An Extra Chair'],
        why:{q:'Why did the neighbor wait in the doorway?',a:'Because they weren\'t sure they were invited',distractors:['Because the door was locked','Because it was raining','Because they were tired']} },
    ],
  },
  food: {
    heroes:[{name:'Chef Pip',kind:'young cook'},{name:'Rosa',kind:'baker'},{name:'Sam',kind:'kid'},{name:'Mina',kind:'child'}],
    settings:[{prose:'in a warm little kitchen',label:'In the kitchen'},{prose:'at a busy farmers market',label:'At the market'},{prose:'in a sunny backyard garden',label:'In the garden'}],
    episodes:[
      { feeling:'proud',
        want:'wanted to bake muffins for the whole class',
        trigger:'mixed the flour, eggs, and ripe mashed bananas',
        problem:'the batter looked too runny to bake just right',
        help:'a parent showed how to add a little more flour',
        solution:'baked a tray of golden muffins that smelled amazing',
        lesson:'following good steps turns a flop into a treat',
        mainIdea:'bakes a treat to share with others',
        detail:'Banana muffins were the class\'s favorite.',
        extra:'Every muffin was gone by the end of the day.',
        vocab:{word:'batter',sentence:'The batter was the soft, wet mix before it was baked.',meaning:'the wet mix before baking',distractors:['the empty pan','the cooled treat','the cold milk']},
        titles:['Muffin Day','[NAME] Bakes','The Golden Treat'],
        why:{q:'Why did [NAME] add more flour?',a:'Because the batter was too runny',distractors:['Because it was too dry','Because it tasted salty','Because the oven was cold']} },
      { feeling:'happy',
        want:'wanted to pick the ripest tomatoes for a family salad',
        trigger:'walked through the garden rows looking for red and round',
        problem:'many tomatoes were still hard and green',
        help:'a wise gardener showed how to spot the ripe ones',
        solution:'gathered a basket of juicy red tomatoes for dinner',
        lesson:'a little know-how helps you make a good choice',
        mainIdea:'learns to pick ripe food from the garden',
        detail:'Ripe tomatoes are soft, red, and smell sweet.',
        extra:'The salad was the best part of dinner.',
        vocab:{word:'ripe',sentence:'A ripe tomato is ready to eat, soft and bright red.',meaning:'grown and ready to eat',distractors:['still growing','already rotten','frozen hard']},
        titles:['Ripe and Red','[NAME] in the Garden','Tomato Time'],
        why:{q:'How did [NAME] know which tomatoes to pick?',a:'A gardener showed how to spot ripe ones',distractors:['[NAME] guessed at random','The tomatoes glowed','A bird picked them']} },
    ],
  },
  transportation: {
    heroes:[{name:'Toot',kind:'little train'},{name:'Bea',kind:'school bus'},{name:'Sky',kind:'small plane'},{name:'Finn',kind:'kid'}],
    settings:[{prose:'on a winding country railway',label:'On the railway'},{prose:'along a busy city road',label:'On the road'},{prose:'at a small grassy airfield',label:'At the airfield'}],
    episodes:[
      { feeling:'proud',
        want:'wanted to carry the mail over the hill to the next town',
        trigger:'chugged up the track with a heavy load of letters',
        problem:'the hill was steep and the wheels began to slow',
        help:'a friendly engine gave a gentle push from behind',
        solution:'rolled over the top and coasted down to the town',
        lesson:'a push from a friend helps you over the hump',
        mainIdea:'carries the mail over a steep hill',
        detail:'The mailbag was stuffed full of letters.',
        extra:'The town cheered as the mail arrived on time.',
        vocab:{word:'steep',sentence:'The steep hill went sharply up, hard to climb.',meaning:'rising sharply and high',distractors:['flat and low','soft and round','wet and muddy']},
        titles:['Over the Hill','[NAME] Carries the Mail','The Big Climb'],
        why:{q:'How did [NAME] get over the hill?',a:'A friendly engine gave a push',distractors:['It flew over','The hill moved away','[NAME] used a balloon']} },
      { feeling:'excited',
        want:'wanted to take the children to school on a foggy morning',
        trigger:'rolled down the street with headlights glowing bright',
        problem:'the fog was so thick the next stop was hard to see',
        help:'a crossing guard waved a bright lantern at each corner',
        solution:'reached every stop safely and got everyone to school',
        lesson:'going slow and careful keeps everyone safe',
        mainIdea:'gets children to school safely in the fog',
        detail:'The fog made the whole street look gray.',
        extra:'The children waved thank you out the windows.',
        vocab:{word:'thick',sentence:'The fog was so thick it was hard to see very far.',meaning:'heavy and hard to see through',distractors:['thin and clear','warm and dry','loud and fast']},
        titles:['The Foggy Morning','[NAME] on the Road','Safe to School'],
        why:{q:'Why was it hard to see the next stop?',a:'Because the fog was very thick',distractors:['Because it was nighttime','Because the lights broke','Because it was snowing']} },
    ],
  },
  seasons: {
    heroes:[{name:'Maple',kind:'kid'},{name:'Sol',kind:'child'},{name:'Wren',kind:'girl'},{name:'Bo',kind:'boy'}],
    settings:[{prose:'in a backyard full of trees',label:'In the backyard'},{prose:'at a park by the pond',label:'At the park'},{prose:'on a quiet country lane',label:'On a country lane'}],
    episodes:[
      { feeling:'joyful',
        want:'wanted to rake the autumn leaves into one giant pile',
        trigger:'swept the red and gold leaves across the whole yard',
        problem:'a gust of wind scattered the leaves everywhere',
        help:'a sibling grabbed a second rake and joined right in',
        solution:'built a huge crunchy pile and jumped right into it',
        lesson:'a chore turns to fun when you share it',
        mainIdea:'rakes autumn leaves and plays in them',
        detail:'In autumn, leaves turn red, orange, and gold.',
        extra:'They jumped in the pile until sunset.',
        vocab:{word:'scattered',sentence:'The wind scattered the leaves, spreading them all around.',meaning:'spread all around',distractors:['stacked them neatly','glued them down','hid them away']},
        titles:['The Leaf Pile','Autumn Fun','[NAME] and the Wind'],
        why:{q:'Why did the leaves go everywhere?',a:'Because a gust of wind scattered them',distractors:['Because it was summer','Because they melted','Because a dog ate them']} },
      { feeling:'happy',
        want:'wanted to build the very first snowman of winter',
        trigger:'rolled three big snowballs across the frosty yard',
        problem:'the top ball kept rolling off and breaking apart',
        help:'a friend packed the snow tight so it would stick',
        solution:'stacked the snowman tall and added a carrot nose',
        lesson:'patience and a friend make the work worthwhile',
        mainIdea:'builds a snowman with a friend in winter',
        detail:'In winter, soft snow covers everything in white.',
        extra:'They named the snowman and waved goodnight.',
        vocab:{word:'frosty',sentence:'The frosty yard was cold and covered in white ice.',meaning:'cold and icy',distractors:['warm and sunny','dry and dusty','green and grassy']},
        titles:['The First Snowman','Winter Fun','[NAME] in the Snow'],
        why:{q:'Why did the top ball keep falling?',a:'Because the snow was not packed tight',distractors:['Because it was too hot','Because it was raining','Because it was nighttime']} },
    ],
  },
  plants: {
    heroes:[{name:'Fern',kind:'kid'},{name:'Basil',kind:'child'},{name:'Posy',kind:'girl'},{name:'Reed',kind:'boy'}],
    settings:[{prose:'in a green vegetable garden',label:'In the garden'},{prose:'on a sunny windowsill',label:'On the windowsill'},{prose:'at a community plant patch',label:'At the plant patch'}],
    episodes:[
      { feeling:'proud',
        want:'wanted to grow a sunflower taller than anyone else\'s',
        trigger:'planted a little seed in a pot of dark, rich soil',
        problem:'days went by and nothing seemed to be happening',
        help:'a wise neighbor explained that seeds grow slowly underground',
        solution:'kept watering until a green sprout pushed up at last',
        lesson:'good things grow for those who wait and care',
        mainIdea:'grows a plant with patience and care',
        detail:'A seed needs water, sun, and time to grow.',
        extra:'By summer the sunflower was taller than [NAME].',
        vocab:{word:'sprout',sentence:'A green sprout, the tiny first part of a plant, popped up.',meaning:'a tiny new plant',distractors:['a dead leaf','a big rock','a fat worm']},
        titles:['The Tall Sunflower','[NAME]\'s Seed','Growing Up'],
        why:{q:'Why did nothing seem to happen at first?',a:'Because seeds grow slowly underground',distractors:['Because the seed was broken','Because it was winter','Because a bird took it']} },
      { feeling:'grateful',
        want:'wanted to save a droopy plant that had stopped growing',
        trigger:'noticed the leaves turning pale and curling down',
        problem:'no one was sure what the little plant needed',
        help:'a gardener checked the soil and found it bone dry',
        solution:'gave the plant a deep drink and moved it to the sun',
        lesson:'paying close attention helps you solve a problem',
        mainIdea:'figures out how to help a sick plant',
        detail:'Plants need water and light to stay healthy.',
        extra:'In a week the leaves stood up green and strong.',
        vocab:{word:'droopy',sentence:'The droopy plant hung down, weak and tired-looking.',meaning:'hanging down weakly',distractors:['standing up strong','bright and shiny','tall and stiff']},
        titles:['Saving the Plant','[NAME] the Helper','Green Again'],
        why:{q:'What was wrong with the plant?',a:'The soil was bone dry and it needed water',distractors:['It had too much water','It was too cold','It needed a bigger pot']} },
    ],
  },
  mysteries: {
    heroes:[{name:'Detective Dot',kind:'kid sleuth'},{name:'Sam',kind:'young detective'},{name:'Iris',kind:'girl'},{name:'Theo',kind:'boy'}],
    settings:[{prose:'in a quiet old library',label:'In the library'},{prose:'around a cozy neighborhood',label:'In the neighborhood'},{prose:'inside a curious little museum',label:'At the museum'}],
    episodes:[
      { feeling:'proud',
        want:'wanted to find out who kept leaving tiny footprints in the hall',
        trigger:'followed a trail of little muddy prints down the corridor',
        problem:'the prints stopped right in front of a closed door',
        help:'a friend remembered seeing the class hamster get loose',
        solution:'opened the door and found the hamster hiding inside',
        lesson:'looking closely at clues solves the puzzle',
        mainIdea:'follows clues to solve a small mystery',
        detail:'The footprints were no bigger than a coin.',
        extra:'The hamster was safe and ready for a snack.',
        vocab:{word:'clues',sentence:'The footprints were clues, hints that help solve a mystery.',meaning:'hints that help solve a puzzle',distractors:['big mistakes','funny jokes','heavy boxes']},
        titles:['The Tiny Footprints','[NAME] Solves It','The Missing Hamster'],
        why:{q:'Who was leaving the footprints?',a:'The class hamster that had gotten loose',distractors:['A tiny ghost','A robber','A puddle of rain']} },
      { feeling:'joyful',
        want:'wanted to find the missing piece of the museum puzzle',
        trigger:'searched every shelf for the one lost puzzle piece',
        problem:'the piece was nowhere to be seen all afternoon',
        help:'a guard remembered sweeping something under a bench',
        solution:'peeked under the bench and found the missing piece',
        lesson:'a calm, careful search beats a frantic one',
        mainIdea:'searches carefully to find a lost piece',
        detail:'The puzzle showed a giant blue whale.',
        extra:'The finished puzzle went on display for all to see.',
        vocab:{word:'searched',sentence:'[NAME] searched, looking everywhere for the lost piece.',meaning:'looked hard for something',distractors:['threw it away','ran outside','took a nap']},
        titles:['The Missing Piece','[NAME] at the Museum','Found It!'],
        why:{q:'Where was the missing piece?',a:'Under a bench where it had been swept',distractors:['Inside the whale tank','In [NAME]\'s pocket','On the moon']} },
    ],
  },
  'school adventures': {
    heroes:[{name:'Ana',kind:'student'},{name:'Jamal',kind:'kid'},{name:'Lin',kind:'girl'},{name:'Theo',kind:'boy'}],
    settings:[{prose:'in a busy classroom',label:'In the classroom'},{prose:'out on the playground',label:'On the playground'},{prose:'in the school art room',label:'In the art room'}],
    episodes:[
      { feeling:'proud',
        want:'wanted to win the class spelling game on Friday',
        trigger:'practiced the tricky words over and over all week',
        problem:'one long word kept getting jumbled up',
        help:'a classmate shared a clever trick to remember it',
        solution:'spelled the word right and grinned from ear to ear',
        lesson:'a smart tip and some practice go a long way',
        mainIdea:'practices hard to do well at school',
        detail:'The tricky word had a silent letter.',
        extra:'The whole class clapped for [NAME].',
        vocab:{word:'jumbled',sentence:'The letters got jumbled, all mixed up in the wrong order.',meaning:'mixed up in a messy way',distractors:['lined up neatly','spelled correctly','painted bright']},
        titles:['The Spelling Game','[NAME]\'s Tricky Word','Friday\'s Win'],
        why:{q:'How did [NAME] finally spell the word?',a:'A classmate shared a trick to remember it',distractors:['[NAME] guessed','The word changed','A teacher said it aloud']} },
      { feeling:'happy',
        want:'wanted to paint a mural for the school hallway',
        trigger:'sketched a big bright design on the long blank wall',
        problem:'there was far too much wall for one painter alone',
        help:'the whole class grabbed brushes and pitched in',
        solution:'painted a colorful mural that filled the hallway',
        lesson:'a big dream comes true when everyone helps',
        mainIdea:'creates a mural with the whole class',
        detail:'The mural showed a garden full of birds.',
        extra:'Every student signed a corner of the mural.',
        vocab:{word:'mural',sentence:'A mural is a big painting made right on a wall.',meaning:'a big painting on a wall',distractors:['a small photo','a paper note','a clay pot']},
        titles:['The Big Mural','[NAME]\'s Wall','Color the Hallway'],
        why:{q:'Why did [NAME] need the whole class?',a:'Because the wall was too big for one painter',distractors:['Because the paint ran out','Because it was raining','Because the bell rang']} },
    ],
  },
};

// flatten pools used for distractors across all topics
const HERO_POOL = [];
const SETTING_LABELS = [];
Object.values(FICTION_PACKS).forEach(p=>{
  p.heroes.forEach(h=> HERO_POOL.push(h));
  p.settings.forEach(s=> SETTING_LABELS.push(s.label));
});

Object.assign(window, { FICTION_PACKS, HERO_POOL, SETTING_LABELS });
